import {afterEach,beforeEach,expect,test} from 'bun:test';
import Database from 'bun:sqlite';
import {existsSync,linkSync,mkdirSync,rmSync,symlinkSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {createTempWorkspace,setEnv} from '../helpers.js';
import {closeDatabase,getDb,initDatabase,insertToolOutputChunk,storeToolOutput} from '../../src/db.js';
import {getUser} from '../../src/db/users.js';
import {createWebSession} from '../../src/db/web-sessions.js';
import {provisionFamilyAccount,updateManagedAccount} from '../../src/db/account-administration.js';
import {createOwnedRoot} from '../../src/db/owned-session-lifecycle.js';
import {resolveRequestPrincipal} from '../../src/channels/web/auth/principal.js';
import {authoriseExecutionIdentity} from '../../src/agent-pool/execution-identity.js';
import {withExecutionIdentity,type ExecutionIdentity} from '../../src/core/execution-context.js';
import {withChatContext} from '../../src/core/chat-context.js';
import {getRootOwnership} from '../../src/db/session-ownership.js';
import {updateAdminToolPolicy} from '../../src/db/family-tool-restrictions.js';
import {requireFamilyToolAccess} from '../../src/agent-pool/family-tool-access.js';
import * as outputs from '../../src/tool-output.js';
import {initializeToolOutputOwnership} from '../../src/db/tool-output-ownership-schema.js';
import {renameChatJid} from '../../src/db/chat-branches.js';

let ws:ReturnType<typeof createTempWorkspace>,restore:()=>void,admin:any,alice:any,bob:any;
function actor(id:string){const login=createWebSession(`token-${id}-${Math.random()}`,id,3600,'passkey');return resolveRequestPrincipal(new Request('https://family.local',{headers:{cookie:'piclaw_session=x'}}),{mode:'family-shared',authEnabled:true},{getSession:()=>login,getUser:()=>getUser(getDb(),id),getLocalDisplayName:()=>''})!;}
function identity(who:any,chat=who.homeChatJid!){return authoriseExecutionIdentity(getDb(),'family-shared',chat,{actorUserId:who.userId,ownerUserId:who.userId,chatJid:chat,kind:'interactive',authenticationSessionId:who.authentication.sessionId!})!;}
function run<T>(snapshot:ExecutionIdentity,call:()=>T|Promise<T>){return withExecutionIdentity(snapshot,()=>withChatContext(snapshot.provenance.chatJid,'web',async()=>call()));}
beforeEach(()=>{ws=createTempWorkspace('owned-tool-output-');restore=setEnv({PICLAW_WORKSPACE:ws.workspace,PICLAW_STORE:ws.store,PICLAW_DATA:ws.data});mkdirSync(join(ws.workspace,'.piclaw'));writeFileSync(join(ws.workspace,'.piclaw/config.json'),JSON.stringify({domains:{access:{mode:'family-shared'}}}));closeDatabase();initDatabase();admin=actor('default');[alice,bob]=['alice','bob'].map(name=>{const user=provisionFamilyAccount(getDb(),admin,{username:name,displayName:name});getDb().query("INSERT INTO webauthn_credentials(user_id,rp_id,credential_id,public_key) VALUES (?,'family.local',?,'key')").run(user.id,name);updateManagedAccount(getDb(),admin,user.id,{enabled:true},{totp:false,passkey:true,rpId:'family.local'});return actor(user.id);});});
afterEach(()=>{closeDatabase();restore();ws.cleanup();});

test('family outputs persist immutable owner/root/source/chat/kind scope and an owner-sharded file',async()=>{const a=identity(alice),saved=await run(a,()=>outputs.saveToolOutput('alice private needle',{source:'read'})),root=getRootOwnership(getDb(),alice.homeChatJid!)!,source=getDb().query('SELECT branch_id FROM chat_branches WHERE chat_jid=?').get(alice.homeChatJid) as {branch_id:string};expect(getDb().query('SELECT owner_user_id,root_branch_id,source_branch_id,chat_jid,execution_kind FROM tool_outputs WHERE id=?').get(saved.id)).toEqual({owner_user_id:alice.userId,root_branch_id:root.rootBranchId,source_branch_id:source.branch_id,chat_jid:alice.homeChatJid,execution_kind:'interactive'});expect(saved.path).toContain('/tool-output/users/');expect(existsSync(saved.path)).toBe(true);expect(await run(a,()=>outputs.searchToolOutput(saved.id,'needle'))).toHaveLength(1);expect(await run(a,()=>outputs.readToolOutputFile(saved.path))).toContain('alice private');for(const sql of ["UPDATE tool_outputs SET owner_user_id='other' WHERE id=?","UPDATE tool_outputs SET chat_jid='other' WHERE id=?"])expect(()=>getDb().query(sql).run(saved.id)).toThrow('immutable');expect(()=>getDb().query("INSERT INTO tool_outputs(id,created_at,owner_user_id) VALUES ('partial','now',?)").run(alice.userId)).toThrow();await expect(run(a,()=>outputs.saveToolOutput('bad',{id:'../escape'}))).rejects.toThrow();await expect(withExecutionIdentity(a,()=>withChatContext(bob.homeChatJid!,'web',async()=>outputs.getToolOutput(saved.id)))).rejects.toThrow();});

test('other owners, other chats and legacy rows cannot resolve a family output handle',async()=>{const a=identity(alice),b=identity(bob),saved=await run(a,()=>outputs.saveToolOutput('alice secret marker',{source:'read'}));expect(await run(b,()=>outputs.getToolOutput(saved.id))).toBeUndefined();expect(await run(b,()=>outputs.searchToolOutput(saved.id,'marker'))).toEqual([]);expect(await run(b,()=>outputs.readToolOutputFile(saved.path))).toBeNull();const root=createOwnedRoot(getDb(),alice,'other'),other=identity(alice,root.chat_jid);expect(await run(other,()=>outputs.getToolOutput(saved.id))).toBeUndefined();storeToolOutput({id:'legacy',created_at:new Date().toISOString(),source:'old',path:null});insertToolOutputChunk('legacy','legacy secret');expect(await run(a,()=>outputs.getToolOutput('legacy'))).toBeUndefined();});

test('stable source branch scope survives permitted internal JID maintenance',async()=>{const a=identity(alice),saved=await run(a,()=>outputs.saveToolOutput('rename marker')),old=alice.homeChatJid!,next=`${old}-renamed`;renameChatJid(old,next);alice=actor(alice.userId);const current=identity(alice,next);expect(await run(current,()=>outputs.searchToolOutput(saved.id,'marker'))).toHaveLength(1);expect(getDb().query('SELECT chat_jid FROM tool_outputs WHERE id=?').get(saved.id)).toEqual({chat_jid:old});});

test('tampered paths, symlink replacements and hard links fail closed',async()=>{const a=identity(alice),saved=await run(a,()=>outputs.saveToolOutput('private path',{source:'read'})),outside=join(ws.workspace,'outside');writeFileSync(outside,'outside');getDb().query('UPDATE tool_outputs SET path=? WHERE id=?').run(outside,saved.id);await expect(run(a,()=>outputs.getToolOutput(saved.id))).rejects.toThrow();getDb().query('UPDATE tool_outputs SET path=? WHERE id=?').run(saved.path,saved.id);rmSync(saved.path);symlinkSync(outside,saved.path);await expect(run(a,()=>outputs.readToolOutputFile(saved.path))).rejects.toThrow();rmSync(saved.path);linkSync(outside,saved.path);await expect(run(a,()=>outputs.readToolOutputFile(saved.path))).rejects.toThrow();});

test('family save rejects a symlinked owner shard before writing outside the data root',async()=>{const a=identity(alice),seed=await run(a,()=>outputs.saveToolOutput('seed',{id:'seed'})),scopeRoot=seed.path.split('/').slice(0,-3).join('/'),outside=join(ws.workspace,'outside-dir');rmSync(scopeRoot,{recursive:true,force:true});mkdirSync(outside);symlinkSync(outside,scopeRoot,'dir');await expect(run(a,()=>outputs.saveToolOutput('escape',{id:'escape'}))).rejects.toThrow();expect(existsSync(join(outside,'escape.log'))).toBe(false);});

test('owner pruning denies tampered paths and symlinked directories without deleting external files',async()=>{const a=identity(alice),old=new Date(Date.now()-2*60*60*1000).toISOString(),saved=await run(a,()=>outputs.saveToolOutput('old',{createdAt:old})),outside=join(ws.workspace,'outside.log');writeFileSync(outside,'keep');getDb().query('UPDATE tool_outputs SET path=? WHERE id=?').run(outside,saved.id);await expect(run(a,()=>outputs.pruneToolOutputs(60*60*1000))).rejects.toThrow();expect(existsSync(outside)).toBe(true);expect(getDb().query('SELECT id FROM tool_outputs WHERE id=?').get(saved.id)).toEqual({id:saved.id});getDb().query('UPDATE tool_outputs SET path=? WHERE id=?').run(saved.path,saved.id);const parts=saved.path.split('/'),shard=parts.slice(0,-3).join('/'),link=join(shard,'escape');symlinkSync(ws.workspace,link,'dir');await expect(run(a,()=>outputs.pruneToolOutputFiles(1))).rejects.toThrow();expect(existsSync(outside)).toBe(true);});

test('scope-specific pruning removes only current chat records and never traverses another shard',async()=>{const old=new Date(Date.now()-2*60*60*1000).toISOString(),a=identity(alice),b=identity(bob),aliceOutput=await run(a,()=>outputs.saveToolOutput('alice old',{createdAt:old})),bobOutput=await run(b,()=>outputs.saveToolOutput('bob old',{createdAt:old}));expect(await run(a,()=>outputs.pruneToolOutputs(60*60*1000))).toBe(1);expect(existsSync(aliceOutput.path)).toBe(false);expect(existsSync(bobOutput.path)).toBe(true);expect(await run(b,()=>outputs.getToolOutput(bobOutput.id))).toBeDefined();});

test('live login and policy revocation deny search without exposing handle existence',async()=>{const a=identity(alice),saved=await run(a,()=>outputs.saveToolOutput('search me',{source:'read'}));expect(await run(a,()=>{requireFamilyToolAccess('search_tool_output');return outputs.searchToolOutput(saved.id,'search');})).toHaveLength(1);updateAdminToolPolicy(getDb(),admin,alice.userId,{confirm_username:'alice',expected_revision:0,denied_tools:['search_tool_output']});const next=identity(alice);await expect(run(next,()=>requireFamilyToolAccess('search_tool_output'))).rejects.toThrow();getDb().query('DELETE FROM web_sessions WHERE session_id=?').run(alice.authentication.sessionId);await expect(run(a,()=>outputs.searchToolOutput(saved.id,'search'))).rejects.toThrow('Tool output access denied');});

test('scoped FTS corruption fails closed rather than reporting no match',async()=>{const a=identity(alice),saved=await run(a,()=>outputs.saveToolOutput('needle'));getDb().exec('DROP TABLE tool_outputs_fts');await expect(run(a,()=>outputs.searchToolOutput(saved.id,'needle'))).rejects.toThrow();});

test('scope revocation during indexed storage rolls back metadata, FTS, file and login mutation',async()=>{const db=getDb(),a=identity(alice);db.exec(`CREATE TRIGGER revoke_during_output AFTER INSERT ON tool_outputs BEGIN DELETE FROM web_sessions WHERE session_id='${alice.authentication.sessionId}'; END;`);const before=db.query('SELECT count(*) n FROM web_sessions').get();await expect(run(a,()=>outputs.saveToolOutput('private indexed content',{id:'revoke-race'}))).rejects.toThrow('Tool output access denied');expect(db.query('SELECT count(*) n FROM tool_outputs').get()).toEqual({n:0});expect(db.query('SELECT count(*) n FROM tool_outputs_fts').get()).toEqual({n:0});expect(db.query('SELECT count(*) n FROM web_sessions').get()).toEqual(before);expect(existsSync(join(ws.data,'tool-output','revoke-race.log'))).toBe(false);});

test('additive scope schema preserves legacy rows as unowned and rejects partial new scope',()=>{const db=new Database(':memory:');try{db.exec(`CREATE TABLE tool_outputs(id TEXT PRIMARY KEY,created_at TEXT NOT NULL,source TEXT,size_bytes INTEGER,line_count INTEGER,summary TEXT,path TEXT);INSERT INTO tool_outputs VALUES('legacy','now','read',1,1,'summary',NULL);`);initializeToolOutputOwnership(db);expect(db.query('SELECT owner_user_id,root_branch_id,source_branch_id,chat_jid,execution_kind FROM tool_outputs').get()).toEqual({owner_user_id:null,root_branch_id:null,source_branch_id:null,chat_jid:null,execution_kind:null});expect(()=>db.query("INSERT INTO tool_outputs(id,created_at,owner_user_id) VALUES('bad','now','owner')").run()).toThrow();}finally{db.close();}});

test('semantic cache is partitioned by owner scope without contaminating shared config modules',async()=>{const fixturePath=new URL('../fixtures/tool-output-owner-cache.ts',import.meta.url).pathname,child=Bun.spawn([process.execPath,'--no-env-file','-e',`import { runOwnerCacheScenario } from ${JSON.stringify(fixturePath)}; await runOwnerCacheScenario();`],{env:{...process.env,PICLAW_WORKSPACE:ws.workspace,PICLAW_STORE:ws.store,PICLAW_DATA:ws.data,PICLAW_DB_IN_MEMORY:'1',PICLAW_TOOL_RESULT_COMPACTION_ENABLED:'1',PICLAW_TOOL_RESULT_COMPACTION_TOOLS:'bash',PICLAW_TOOL_OUTPUT_STORE_BYTES:'8',PICLAW_TOOL_OUTPUT_STORE_LINES:'2'},stdout:'pipe',stderr:'pipe'});const[code,stdout,stderr]=await Promise.all([child.exited,new Response(child.stdout).text(),new Response(child.stderr).text()]);expect(code,stderr||stdout).toBe(0);expect(stdout).toContain('OWNER_CACHE_OK');});
