import {Database} from 'bun:sqlite';
import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
const dir=import.meta.dir;const read=(p:string)=>JSON.parse(readFileSync(p,'utf8')); const save=(n:string,v:any)=>writeFileSync(`${dir}/${n}.json`,JSON.stringify(v,null,2)+'\n');
const cutoff='2026-09-05T20:19:00.000Z';const since='2026-08-29T20:19:00.000Z';const day='2026-09-04T20:19:00.000Z';
const db=new Database('/workspace/.piclaw/store/messages.db',{readonly:true});
const rows=db.query(`SELECT provider,model,run_at,input_tokens AS input,output_tokens AS output,cache_read_tokens AS cr,cache_write_tokens AS cw,reasoning_tokens AS reasoning,total_tokens AS total,cost_total AS cost,cost_provenance AS provenance,usage_source FROM token_usage WHERE run_at>=? AND run_at<? ORDER BY run_at`).all(since,cutoff) as any[]; db.close();
const zero=()=>({requests:0,input:0,output:0,cr:0,cw:0,reasoning:0,total:0,cost:0,accounted:0,longRequests:0,longAccounted:0,zeroCostRequests:0,zeroCostTokens:0});
function agg(rs:any[]){let s=zero();for(const r of rs){s.requests++;for(const k of ['input','output','cr','cw','reasoning','total','cost'])s[k]+=r[k]||0;const a=r.input+r.output+r.cr+r.cw;s.accounted+=a;if(r.input+r.cr+r.cw>272000){s.longRequests++;s.longAccounted+=a;}if(!r.cost){s.zeroCostRequests++;s.zeroCostTokens+=a;}}return s;}
const keys=[...new Set(rows.map(r=>`${r.provider}/${r.model}`))];
const workload={since,cutoff,scope:'Smith local ledger, all chats; seven-day primary and 24-hour sensitivity',sevenDays:agg(rows),last24h:agg(rows.filter(r=>r.run_at>=day)),byModel:keys.map(k=>({key:k,...agg(rows.filter(r=>`${r.provider}/${r.model}`===k))})).sort((a,b)=>b.accounted-a.accounted),byPromptBand:{short:agg(rows.filter(r=>r.input+r.cr+r.cw<=272000)),long:agg(rows.filter(r=>r.input+r.cr+r.cw>272000))},bySource:[...new Set(rows.map(r=>r.usage_source))].map(s=>({source:s,...agg(rows.filter(r=>r.usage_source===s))}))};save('workload',workload);
// Whitelist only non-secret catalogue fields. This file contains NO auth/config secrets.
const catDir='/opt/piclaw/current/app/node_modules/@earendil-works/pi-ai/dist/providers/data';const catalog:any[]=[];
for(const f of readdirSync(catDir).filter(x=>x.endsWith('.json')&&!x.startsWith('.'))){const j=read(`${catDir}/${f}`);for(const g of Object.values(j) as any[])for(const m of Object.values(g) as any[])if(m?.id)catalog.push({provider:f.slice(0,-5),id:m.id,name:m.name,api:m.api,cost:m.cost,contextWindow:m.contextWindow,maxTokens:m.maxTokens});}save('installed-catalogue',catalog);
const rates:any[]=[];function add(provider:string,id:string,name:string,input:number,output:number,cr:number|null,cw:number|null,extra:any={}){for(const v of [input,output,cr,cw])if(v!==null&&(!Number.isFinite(v)||v<0))return;rates.push({provider,id,name,input,output,cr,cw,cacheReadPolicy:cr===null?'ordinary-input fallback':'published',cacheWritePolicy:cw===null?'ordinary-input fallback':'published',currency:'USD',unit:'per 1M tokens',...extra});}
// Parse first-party standard tables only. Dash means unavailable, never free.
const oa=readFileSync(`${dir}/sources/openai-pricing.md`,'utf8').split('### Standard pricing data')[1].split('Regional processing')[0];
for(const l of oa.split('\n').filter(l=>/^\| (gpt|o\d|chatgpt)/.test(l))){const c=l.split('|').slice(1,-1).map(x=>x.trim());const num=(s:string)=>s==='-'?null:Number(s.replace(/[$,]/g,''));const id=c[0].split(' ')[0];add('openai',id,id,num(c[1])!,num(c[4])!,num(c[2]),num(c[3]),{source:'https://developers.openai.com/api/docs/pricing.md',evidence:'public-first-party',threshold:num(c[5])===null?null:(id.includes('luna')?200000:272000),long:num(c[5])===null?null:{input:num(c[5]),cr:num(c[6]),cw:num(c[7]),output:num(c[8])}});}
const an=readFileSync(`${dir}/sources/anthropic-pricing.md`,'utf8').split('## Model pricing')[1].split('*1 Cache')[0];
for(const l of an.split('\n').filter(l=>l.startsWith('| Claude '))){const c=l.split('|').slice(1,-1).map(x=>x.trim());const name=c[0].split(' (')[0];const num=(s:string)=>Number(s.match(/\$([\d.]+)/)![1]);add('anthropic',name.toLowerCase().replaceAll(' ','-'),name,num(c[1]),num(c[5]),num(c[4]),num(c[2]),{cw1h:num(c[3]),source:'https://platform.claude.com/docs/en/about-claude/pricing.md',evidence:'public-first-party',restricted:name.includes('Mythos'),retired:c[0].includes('retired')});}
const or=read(`${dir}/sources/openrouter-models.json`);for(const m of or.data){const p=m.pricing;const n=(k:string)=>p[k]===undefined?null:Number(p[k])*1e6;add('openrouter',m.id,m.name,n('prompt')!,n('completion')!,n('input_cache_read'),n('input_cache_write'),{source:'https://openrouter.ai/api/v1/models',evidence:'public-route',contextWindow:m.context_length,huggingFaceId:m.hugging_face_id||null,description:m.description,pricingOverrides:p.overrides||[],rawPricing:p});}
// Public Copilot prices verified separately; names/tiers match these first-party meters.
for(const r of [...rates].filter(r=>['openai','anthropic'].includes(r.provider)&&!r.restricted&&!r.retired))if(readFileSync(`${dir}/sources/copilot-pricing.md`,'utf8').includes(r.name==='gpt-6-astra'?'GPT-6 Astra':r.name.startsWith('gpt-')?r.name.replace('gpt-','GPT-').replace('-sol',' Sol').replace('-terra',' Terra').replace('-luna',' Luna'):r.name)){rates.push({...r,provider:'github-copilot',source:'https://docs.github.com/en/copilot/reference/copilot-billing/models-and-pricing.md',billing:'AI credit consumption; subscription allowance/budget not deducted'});}
for(const id of ['gpt-6-astra','gpt-5.6-sol','gpt-5.6-terra','gpt-5.5','gpt-5.4']){const r=rates.find(r=>r.provider==='openai'&&r.id===id);rates.push({...r,provider:'openai-codex',evidence:'public-API-equivalent',billing:'ChatGPT subscription; API-equivalent only, not an invoice'});}
for(const r of catalog.filter(r=>r.provider==='cerebras'))if(!rates.some(x=>x.provider===r.provider&&x.id===r.id))add(r.provider,r.id,r.name,r.cost.input,r.cost.output,r.cost.cacheRead>0?r.cost.cacheRead:null,r.cost.cacheWrite>0?r.cost.cacheWrite:null,{source:`installed:${catDir}/cerebras.json`,evidence:'catalogue-only',contextWindow:r.contextWindow});
if(!rates.some(r=>r.provider==='cerebras'&&r.id==='zai-glm-4.7'))add('cerebras','zai-glm-4.7','GLM 4.7',null as any,null as any,null,null,{source:'Configured local model has zero placeholder cost; public rate not yet verified',evidence:'unpriced'});
// Public Azure page is dynamic; do not silently borrow native/OpenRouter rates.
for(const [id,name,input,output] of [['deepseek-v4-flash','DeepSeek V4 Flash',0.19,0.51],['deepseek-v4-pro','DeepSeek V4 Pro',null,null],['mistral-large-3','Mistral Large 3',0.5,1.5]] as any[])add('azure-foundry',id,name,input,output,null,null,{source:'historical local pricing reference 2026-08-03; Azure live numeric verification incomplete',evidence:'historical-unverified'});
for(const id of ['gpt-5.4-pro','gpt-5.4','gpt-5.3-codex']){const r=rates.find(r=>r.provider==='openai'&&r.id===id);if(r)rates.push({...r,provider:'azure-openai',evidence:'native-reference-only',billing:'Azure regional/contract quote not verified; shown as native reference, not an Azure tariff'});}
for(const r of rates){if(['openai','openai-codex','github-copilot'].includes(r.provider)&&['gpt-6-astra','gpt-5.6-sol','gpt-5.6-terra'].includes(r.id)){r.contextWindow=1050000;r.contextSource=`https://developers.openai.com/api/docs/models/${r.id}.md`;}if(r.provider==='cerebras'&&r.id==='gpt-oss-120b'){r.evidence='public-first-party';r.source='https://inference-docs.cerebras.ai/models/openai-oss.md';}}
// GPT-5.3 Codex is in the separate Codex table; exact current published standard rate.
if(!rates.some(r=>r.provider==='azure-openai'&&r.id==='gpt-5.3-codex'))add('azure-openai','gpt-5.3-codex','GPT-5.3 Codex',1.75,14,.175,null,{evidence:'native-reference-only',source:'https://developers.openai.com/api/docs/pricing.md',billing:'Not a verified Azure tariff'});
for(const m of catalog)if(!rates.some(r=>r.provider===m.provider&&r.id===m.id)&&m.cost){const c=m.cost;add(m.provider,m.id,m.name,c.input===0?null as any:c.input,c.output===0?null as any:c.output,c.cacheRead>0?c.cacheRead:null,c.cacheWrite>0?c.cacheWrite:null,{source:`installed:${catDir}/${m.provider}.json`,evidence:'catalogue-only',contextWindow:m.contextWindow,tiers:c.tiers||null});}
save('pricing-catalogue',{asOf:cutoff,retrievedAt:new Date().toISOString(),notes:['Standard processing only unless model ID names batch.','null rates mean unknown; scenario fallback for cache is ordinary input.','No runtime configuration or historical ledger costs are rewritten.'],rates});
// Counterfactual replay: normalised independent categories. Reasoning is NOT added again.
function estimate(rate:any,rs:any[],cold=false,oneHour=false,tiers=true){if(rate.input===null||rate.output===null)return null;let dollars=0;let longN=0;for(const r of rs){const prompt=r.input+r.cr+r.cw;let p={...rate};if(tiers&&rate.long&&prompt>rate.threshold){p={...p,...rate.long};longN++;}if(tiers&&rate.pricingOverrides?.length){for(const o of rate.pricingOverrides)if(prompt>=o.min_prompt_tokens){const q=o;p={...p,input:Number(q.prompt)*1e6,output:Number(q.completion)*1e6,cr:q.input_cache_read===undefined?null:Number(q.input_cache_read)*1e6,cw:q.input_cache_write===undefined?null:Number(q.input_cache_write)*1e6};longN++;}}
 dollars+=(cold?prompt*p.input:r.input*p.input+r.cr*(p.cr??p.input)+r.cw*(oneHour?(p.cw1h??p.cw??p.input):(p.cw??p.input))) /1e6+r.output*p.output/1e6;}return {usd:dollars,perDay:dollars/(rs===rows?7:1),longRequests:longN};}
const groups:any={
 'GitHub Copilot':['github-copilot/gpt-6-astra','github-copilot/claude-fable-5.1','github-copilot/gpt-5.6-sol'],
 'OpenAI Codex':['openai-codex/gpt-6-astra','openai-codex/gpt-5.6-sol','openai-codex/gpt-5.6-terra'],
 'Anthropic public API':['anthropic/claude-fable-5.1','anthropic/claude-fable-5','anthropic/claude-opus-5'],
 'OpenRouter premium/value shortlist':['openrouter/anthropic/claude-fable-5.1','openrouter/openai/gpt-6-astra','openrouter/deepseek/deepseek-v4-pro-0813'],
 'Cerebras':['cerebras/gemma-4-31b','cerebras/gpt-oss-120b','cerebras/zai-glm-4.7'],
 'Azure OpenAI (native reference only)':['azure-openai/gpt-5.4-pro','azure-openai/gpt-5.4','azure-openai/gpt-5.3-codex'],
 'Azure Foundry (verification incomplete)':['azure-foundry/deepseek-v4-pro','azure-foundry/deepseek-v4-flash','azure-foundry/mistral-large-3'],
 'Open-weight capability candidates via OpenRouter':['openrouter/deepseek/deepseek-v4-pro-0813','openrouter/moonshotai/kimi-k3','openrouter/minimax/minimax-m3']};
const extra=['openrouter/openai/gpt-5.6-sol','openrouter/anthropic/claude-fable-5','openrouter/anthropic/claude-opus-5','openrouter/deepseek/deepseek-v4-flash-0731','openrouter/z-ai/glm-5.2','openai/gpt-5.5','openai/gpt-5.6-sol','openai/gpt-5.6-terra','anthropic/claude-sonnet-5','anthropic/claude-sonnet-4.6'];
const selected=[...new Set([...Object.values(groups).flat(),...extra])];const results=selected.map((key:string)=>{const rate=rates.find(r=>`${r.provider}/${r.id}`===key);if(!rate)throw new Error(`Missing candidate ${key}`);const ctx=rate.contextWindow??catalog.find(c=>c.provider===rate.provider&&c.id===rate.id)?.contextWindow??null;return {key,rate,contextWindow:ctx,overContextRequests:ctx?rows.filter(r=>r.input+r.cr+r.cw>ctx).length:null,sevenDay:estimate(rate,rows),baseOnly:estimate(rate,rows,false,false,false),cold:estimate(rate,rows,true),oneHour:estimate(rate,rows,false,true),last24h:estimate(rate,rows.filter(r=>r.run_at>=day))};});save('comparison',{groups,results});
console.log(JSON.stringify({workload,rateCount:rates.length,results:results.map(r=>({key:r.key,cost:r.sevenDay?.usd,cold:r.cold?.usd}))},null,2));
