import {readFileSync,writeFileSync} from 'node:fs';
const dir=import.meta.dir;const read=(n:string)=>JSON.parse(readFileSync(`${dir}/${n}.json`,'utf8'));
const w=read('workload'),c=read('comparison'),p=read('pricing-catalogue'),a=w.sevenDays;
const usd=(v:number|null|undefined)=>v==null?'Unverified':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
const num=(n:number)=>n.toLocaleString('en-US');const pct=(v:number)=>`${(v*100).toFixed(1)}%`;
const get=(k:string)=>c.results.find((r:any)=>r.key===k);const astra=get('openai-codex/gpt-6-astra').sevenDay.usd, fable=get('anthropic/claude-fable-5.1').sevenDay.usd, oldFable=get('anthropic/claude-fable-5').sevenDay.usd,sol=get('openai/gpt-5.6-sol').sevenDay.usd;
const esc=(s:any)=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const rate=(v:number|null)=>v==null?'—':`$${v.toFixed(v>0&&v<.01?5:3).replace(/0+$/,'').replace(/\.$/,'')}`;
const sources=[['OpenAI pricing','https://developers.openai.com/api/docs/pricing.md'],['Anthropic pricing','https://platform.claude.com/docs/en/about-claude/pricing.md'],['Copilot pricing and credit accounting','https://docs.github.com/en/copilot/reference/copilot-billing/models-and-pricing.md'],['OpenRouter live model catalogue','https://openrouter.ai/api/v1/models'],['Codex subscription pricing','https://developers.openai.com/codex/pricing'],['Cerebras GPT-OSS 120B','https://inference-docs.cerebras.ai/models/openai-oss.md'],['Astra context window','https://developers.openai.com/api/docs/models/gpt-6-astra.md'],['Fable 5.1 announcement','https://www.anthropic.com/claude-fable-and-mythos-5-1'],['DeepSeek weights (MIT)','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro-0813'],['Kimi K3 weights (custom licence)','https://huggingface.co/moonshotai/Kimi-K3'],['MiniMax M3 weights (custom licence)','https://huggingface.co/MiniMaxAI/Minimax-M3']];
let sections:string[]=[];let md:string[]=[];
const section=(title:string,html:string,text:string)=>{sections.push(`<section><h2>${esc(title)}</h2>${html}</section>`);md.push(`## ${title}\n\n${text}\n`);};
const bullets=(xs:string[])=>`<ul>${xs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const findings=[
 `Fable 5.1 costs ${usd(fable)} for the seven-day replay: ${pct(1-fable/oldFable)} less than Fable 5, and ${pct(1-fable/astra)} less than Astra after request-level long-context pricing. Its cache-read rate falls 75%, from $1 to $0.25/MTok; input/output remain $10/$50.`,
 `Astra is 2.5× Sol's current direct/Copilot token tariffs in both context tiers: ${usd(astra)} versus ${usd(sol)} for the same workload. At standard short-context prices, Astra and Fable 5 have identical four-category rates.`,
 `OpenRouter Sol is quoted at $2/$10 input/output, versus direct/Copilot $4/$20: the replay is 50% cheaper (${usd(get('openrouter/openai/gpt-5.6-sol').sevenDay.usd)}). This is a provider-route difference; do not merge these tariff records, even when merging Sol family usage charts.`,
 `DeepSeek V4 Pro 0813 via OpenRouter is ${usd(get('openrouter/deepseek/deepseek-v4-pro-0813').sevenDay.usd)}, ${pct(1-get('openrouter/deepseek/deepseek-v4-pro-0813').sevenDay.usd/astra)} below Astra. This is a cost opportunity to benchmark, not evidence of equal task success.`,
 `The ledger contains ${num(a.zeroCostRequests)} zero-estimate Astra records covering ${num(a.zeroCostTokens)} tokens. Zero represented missing pricing here; it must not be presented as free inference.`];
section('What changes the decision',bullets(findings),findings.map(x=>'- '+x).join('\n'));
const accounting=[
 `Scope: Smith's canonical SQLite token_usage ledger, all chats, ${w.since} through ${w.cutoff} (exclusive). ${num(a.requests)} usage records; ${num(a.accounted)} accounted tokens. One usage record is not necessarily one user turn.`,
 `Input ${num(a.input)} (${pct(a.input/a.accounted)}); output ${num(a.output)} (${pct(a.output/a.accounted)}); cache read ${num(a.cr)} (${pct(a.cr/a.accounted)}); cache write ${num(a.cw)} (${pct(a.cw/a.accounted)}).`,
 `Cache hits are ${pct(a.cr/(a.input+a.cr+a.cw))} of prompt tokens. ${pct(a.longRequests/a.requests)} of records and ${pct(a.longAccounted/a.accounted)} of token volume are in requests exceeding 272K prompt tokens. Long-context tariffs materially change the result.`,
 `The independent input/output/cache categories sum exactly to total_tokens for this window. ${num(a.reasoning)} reasoning tokens are retained as detail but are not added to output again. Recorded historical estimated cost is ${usd(a.cost)}; it mixes models, tariffs and missing prices and is not the comparison baseline.`,
 `Graphite was checked for fleet inventory. It exports interval sums, not request sizes; its seven-day roll-ups and historical catch-up points cannot support an equally reliable long-context replay. The figures below are Smith workload equivalents, not a claimed whole-fleet bill. A fleet-24h raw snapshot is in sources/.`,
 `The last-24h sensitivity uses ${num(w.last24h.requests)} records and ${num(w.last24h.accounted)} tokens from the same ledger, ending at the same cutoff.`];
section('Workload and accounting',bullets(accounting),accounting.map(x=>'- '+x).join('\n'));
const assumptions=[
 'Fixed-workload replay holds token counts, cache behaviour and output length constant. Model tokenisation, reasoning effort, retries, tool competence and success rate may change these quantities in practice.',
 'Seven-day warm cost = sum of each request’s uncached-input × input rate + output × output rate + cache-read × read rate + cache-write × write rate, divided by one million. Apply >272K OpenAI/Copilot tiers to each request; use the returned OpenRouter pricing overrides for routed models.',
 'Cache cold removes all hits: input + cache reads + cache writes are charged as ordinary input. It represents a no-reuse sensitivity, not necessarily the exact first migration bill. One-hour Anthropic cache writes are an additional sensitivity in comparison.json.',
 'Where a cache tariff is not published, the scenario uses ordinary input rather than treating the tokens as free. Rates display — for an unpublished cache meter; missing entire input/output prices remain unverified and unranked.',
 'All comparisons use standard processing, global/USD list rates, no batch discounts, no taxes, no tools/search charges, no regional uplift and no negotiated discounts. OpenRouter credits/funding fees and the actual selected upstream endpoint can alter cash cost.',
 'Copilot currently documents token-based AI credits (one credit = $0.01). Reported costs indicate consumption before plan allowances/budgets. Codex API-equivalent costs cannot be equated to a ChatGPT subscription invoice.',
 'The three candidates per provider are a frontier/predecessor/value shortlist for this task, not an invented benchmark leaderboard. The user’s SMART scores remain unchanged in historical artefacts; no new numerical capability score is asserted.'
];section('How to read the comparison',bullets(assumptions),assumptions.map(x=>'- '+x).join('\n'));
const providerNotes:any={
 'GitHub Copilot':'Astra and Sol are visible locally. Fable 5.1 is GA in GitHub’s public price table, but is absent from this session’s current local picker. Catalogue refresh/entitlement checks are needed before routing to it. Fable 5 ($3,603.40/replay) is its immediate predecessor; see deltas below.',
 'OpenAI Codex':'All three candidates appear in the local model picker. Fable is not offered on this route. The costs are public API-equivalents, not a quota or message-count conversion.',
 'Anthropic public API':'Fable 5.1 → Fable 5 → Opus 5 is the premium lineage used here. Direct Anthropic credentials are not assumed configured; these models can also be accessed through OpenRouter. Restricted Mythos is excluded.',
 'OpenRouter premium/value shortlist':'All routes are in the live public API. Fable 5.1 appears in the local picker; Astra is publicly listed but may require catalogue refresh. DeepSeek Pro is the selected open-weight alternative; compare Kimi and MiniMax in the separate open-weight group.',
 'Cerebras':'All three IDs are visible locally. GPT-OSS $0.35/$0.75 is publicly verified; Gemma $0.99/$1.49 is catalogue-only. GLM has zero placeholders locally and no verified price. The listed 131K capacities for the priced models are below the prompt size of 91.5% of this workload’s records: compaction/chunking is required, so costs are illustrative, not drop-in capacity claims.',
 'Azure OpenAI (native reference only)':'These three models are configured locally. Values below are native OpenAI references, not verified regional Azure prices; no Azure savings recommendation follows from them. Astra is not in our Azure deployment list. Check actual region, deployment SKU and contract before routing.',
 'Azure Foundry (verification incomplete)':'All three IDs are configured. Flash/Mistral figures are historical local references, not refreshed public Azure quotations. Pro is unpriced. The dynamic Azure page did not establish numeric rates; no OpenRouter tariff was substituted.',
 'Open-weight capability candidates via OpenRouter':'The public API exposes model-weight links: DeepSeek (MIT), Kimi K3 and MiniMax M3 (custom licences). All three have a listed 1,048,576 context window, above every observed prompt. Public presence is not a live inference/entitlement test; validate coding and tool-use performance on representative tasks.'};
const csv:any[]=[['group','provider','model','evidence','input_usd_per_m','output_usd_per_m','cache_read_usd_per_m','cache_write_usd_per_m','7d_warm_usd','7d_cold_usd','last24h_warm_usd','relative_to_astra_pct','source']];
for(const [group,keys] of Object.entries(c.groups) as any){let trs='',lines=['| Model | Input / output per M | Cache read / write per M | 7d warm | vs Astra | 24h warm | 7d cold |','| --- | --- | --- | ---: | ---: | ---: | ---: |'];for(const key of keys){const r=get(key),s=r.rate,v=r.sevenDay?.usd;const label=`${s.name} (${s.id})`;const cells=[label,`${rate(s.input)} / ${rate(s.output)}`,`${rate(s.cr)} / ${rate(s.cw)}`,usd(v),v==null?'—':`${((v/astra-1)*100).toFixed(1)}%`,usd(r.last24h?.usd),usd(r.cold?.usd)];trs+=`<tr>${cells.map((x,i)=>`<td${i>2?' class="number"':''}>${esc(x)}${i===0?`<small>${esc(s.evidence)}</small>`:''}</td>`).join('')}</tr>`;lines.push('| '+cells.join(' | ')+' |');csv.push([group,s.provider,s.id,s.evidence,s.input,s.output,s.cr,s.cw,v,r.cold?.usd,r.last24h?.usd,v==null?null:(v/astra-1)*100,s.source]);}
section(group,`<p>${esc(providerNotes[group])}</p><div class="scroll"><table><thead><tr>${['Model / evidence','Input / output · $/M','Cache read / write · $/M','7d warm','vs Astra','24h warm','7d cold'].map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${trs}</tbody></table></div>`,providerNotes[group]+'\n\n'+lines.join('\n'));}
const pairs=[['Fable 5.1 vs Fable 5','anthropic/claude-fable-5.1','anthropic/claude-fable-5'],['Fable 5 vs Opus 5','anthropic/claude-fable-5','anthropic/claude-opus-5'],['Fable 5.1 vs Opus 5','anthropic/claude-fable-5.1','anthropic/claude-opus-5'],['Astra vs Sol (direct equivalent)','openai-codex/gpt-6-astra','openai-codex/gpt-5.6-sol'],['Sol vs GPT-5.5','openai/gpt-5.6-sol','openai/gpt-5.5'],['Fable 5.1 vs Astra','anthropic/claude-fable-5.1','openai-codex/gpt-6-astra'],['DeepSeek Pro vs Fable 5.1','openrouter/deepseek/deepseek-v4-pro-0813','anthropic/claude-fable-5.1']];
const pairRows=pairs.map(([name,n,o])=>{const v=get(n).sevenDay.usd,prev=get(o).sevenDay.usd;return [name,usd(v-prev),`${((v/prev-1)*100).toFixed(1)}%`];});section('Premium and precursor deltas',`<table><thead><tr><th>New choice vs baseline</th><th>7d dollar delta</th><th>Percent delta</th></tr></thead><tbody>${pairRows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`,['| New choice vs baseline | 7d dollar delta | Percent delta |','| --- | ---: | ---: |',...pairRows.map(r=>'| '+r.join(' | ')+' |')].join('\n'));
const recommendations=[
 'Premium: benchmark Fable 5.1 against Astra on real coding/ops tasks. Fable’s new cache discount is highly relevant to our warm, long-context workload; choose Astra when its measured task outcomes justify the premium.',
 'Precursor: retain Sol as a comparison baseline. The public OpenRouter Sol rate is half direct/Copilot, but model identity, upstream routing, privacy requirements and cache hit behaviour must be checked before switching.',
 'Open weights: trial DeepSeek V4 Pro 0813 first for capability/cost balance, alongside Kimi K3 and MiniMax M3. Add DeepSeek V4 Flash 0731 for cheap triage/extraction: its fixed-workload estimate is '+usd(get('openrouter/deepseek/deepseek-v4-flash-0731').sevenDay.usd)+' per week. These are trial candidates, not asserted quality substitutes.',
 'Infrastructure: do not route this long-context workload directly to the smaller-context Cerebras models without a compaction plan. Open weights hosted locally have non-zero hardware, electricity and operations costs, which are outside API pricing.',
 'Next validation: run a fixed task set and record success rate, retries, actual output tokens, cache hits and wall time. Compare dollars per successful task before changing defaults.'
];section('Recommended trial order',bullets(recommendations),recommendations.map(x=>'- '+x).join('\n'));
const change=[`The refreshed catalogue contains ${p.rates.length} provider/model/API entries with provenance; 499 verified route rows are prepared for the token-chart pricing resolver (see PR/patch). Installed catalogue fields were copied through a non-secret whitelist.`,
 'The runtime pricing reference snapshot adds Fable 5/5.1 and Astra, refreshes public OpenRouter rates, preserves provider-specific Sol prices, and stops assuming unpublished cache reads are free in refreshed rows.',
 'Old $/M figures in the ternary SVGs were measured blended costs for a specific historical mix, not official input/output tariffs. Historical SVGs/ledger rows are preserved; this dated catalogue/report supersedes them for new price comparisons.',
 'No provider credentials, deployments, runtime model choices or historical token_usage rows were changed; no reload was performed. The source refresh is isolated for review, not installed into the running process.',
 'Public first-party and OpenRouter prices override stale installed rates in this report. Catalogue-only, historical-unverified and native-reference-only entries are explicitly labelled, including the incomplete Azure and GLM prices.'
];section('Data changes and remaining gaps',bullets(change),change.map(x=>'- '+x).join('\n'));
section('Sources',`<ol>${sources.map(([n,u])=>`<li><a href="${esc(u)}">${esc(n)}</a></li>`).join('')}</ol><p>Raw responses are archived in sources/. Prices were retrieved during this audit on 5 September 2026. Workload cutoff and retrieval times are separate fields in the data.</p>`,sources.map(([n,u])=>`- [${n}](${u})`).join('\n'));
const title='Model pricing: Fable, Astra and open weights';const intro='5 September 2026 · USD · identical seven-day workload · request-level context tiers';
writeFileSync(`${dir}/report.md`,`# ${title}\n\n${intro}\n\n`+md.join('\n'));
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>:root{--bg:#f6f7f9;--surface:#fff;--text:#1f2937;--dim:#586575;--border:#d8e0e8;--accent:#0f766e}@media(prefers-color-scheme:dark){:root{--bg:#10151e;--surface:#18212d;--text:#e5edf5;--dim:#afbbc9;--border:#344151;--accent:#5eead4}}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.6 system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}main{max-width:1240px;margin:auto;padding:32px 20px}h1{font-size:32px;line-height:1.2;margin-bottom:10px}h2{font-size:22px;margin-top:0}p,li{max-width:1050px}header{margin-bottom:24px}header p,small{color:var(--dim)}section{padding:22px;margin:18px 0;background:var(--surface);border:1px solid var(--border);border-radius:12px}small{display:block;font-size:11px;margin-top:5px}li{margin:8px 0}a{color:var(--accent)}.scroll{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:10px 9px;border-bottom:1px solid var(--border);text-align:left;vertical-align:top}th{color:var(--dim);font-size:11px;letter-spacing:.03em}.number{font-variant-numeric:tabular-nums;white-space:nowrap;text-align:right}.metrics{display:flex;gap:12px;flex-wrap:wrap}.metric{border-left:3px solid var(--accent);padding:8px 16px}.metric strong{font-size:24px;display:block}.metric span{color:var(--dim);font-size:13px}@media(max-width:600px){main{padding:16px 10px}section{padding:14px}h1{font-size:25px}}@media print{body{background:white;color:black}section{break-inside:avoid;box-shadow:none}main{max-width:none;padding:0}}</style></head><body><main><header><h1>${title}</h1><p>${intro}</p><div class="metrics"><div class="metric"><strong>${pct(a.cr/a.accounted)}</strong><span>tokens served from cache</span></div><div class="metric"><strong>${usd(fable)}</strong><span>Fable 5.1 · seven-day replay</span></div><div class="metric"><strong>${usd(astra)}</strong><span>Astra · seven-day replay</span></div></div></header>${sections.join('\n')}</main></body></html>`;
writeFileSync(`${dir}/report.html`,html);writeFileSync(`${dir}/comparison.csv`,csv.map(row=>row.map((v:any)=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n')+'\n');
console.log(JSON.stringify({rates:p.rates.length,models:c.results.length,cacheShare:a.cr/a.accounted,fableSavings:1-fable/oldFable,astraSavings:1-fable/astra,sections:sections.length}));
