import {useEffect,useRef,useState} from 'preact/hooks';
import {createMcpServerSettingsController,INITIAL_MCP_SERVERS,MCP_SERVER_FIELDS,patchFromForm,type McpServerSettingsState} from '../../../../../../src/ui/mcp-server-settings-model';
export function McpServersSection({busy=false,onApplying=(_applying:boolean)=>{}}:{busy?:boolean;onApplying?:(applying:boolean)=>void}={}){
 const[state,setState]=useState<McpServerSettingsState>(INITIAL_MCP_SERVERS),[name,setName]=useState(''),[values,setValues]=useState<Record<string,string>>({}),[ack,setAck]=useState(false),[error,setError]=useState('');
 const controller=useRef<ReturnType<typeof createMcpServerSettingsController>|null>(null);
 useEffect(()=>{const current=createMcpServerSettingsController(setState);controller.current=current;void current.refresh();return()=>{current.dispose();controller.current=null;};},[]);
 useEffect(()=>{onApplying(state.applying);},[state.applying]);
 const edit=(nextName:string,nextValues:Record<string,string>)=>{setAck(false);setError('');try{controller.current?.edit({name:nextName,action:'update',patch:patchFromForm(nextValues)});}catch{setError('Use valid JSON for array, object, boolean and numeric fields.');controller.current?.edit({name:nextName,action:'update',patch:{}});}};
 return <section className="mcp-server-editor" aria-label="MCP server editor"><h3>Adapter servers</h3><p className="settings-panel__description">Only the local project override is changed. Blank fields preserve existing values; null removes a local field and may reveal an inherited value. Private arguments/maps and advanced fields are withheld and preserved. Never paste a secret: use environment or keychain references.</p>
 <button className="settings-panel__button" type="button" disabled={busy||state.loading} onClick={()=>void controller.current?.refresh()}>Refresh servers</button>
 {state.error&&<p role="alert" className="settings-panel__error">{state.error}</p>}{error&&<p role="alert" className="settings-panel__error">{error}</p>}
 {state.payload&&<><p className="settings-panel__description">Server runtime: {state.payload.phase}. Apply interrupts active turns and reloads extensions across all chats; chat history is retained.</p><ul>{state.payload.servers.map(row=><li><button type="button" disabled={state.applying||busy} onClick={()=>{setName(row.name);setValues({});edit(row.name,{});}}>{row.name}</button> — {row.enabled?'enabled':'disabled'}, {row.localOverride?'local override':'inherited'}{row.withheldFields.length?` (private/advanced fields preserved: ${row.withheldFields.join(', ')})`:''}</li>)}</ul></>}
 <label className="settings-panel__label" htmlFor="mcp-server-name">Server name</label><input className="settings-panel__input" id="mcp-server-name" value={name} disabled={state.applying||busy} onInput={e=>{const next=e.currentTarget.value;setName(next);edit(next,values);}} />
 <details><summary>Transport, authentication references, exposure and timeouts</summary>{MCP_SERVER_FIELDS.map(([field,label])=><div className="settings-panel__field"><label className="settings-panel__label" htmlFor={`mcp-server-${field}`}>{label}</label><input className="settings-panel__input" id={`mcp-server-${field}`} value={values[field]??''} disabled={state.applying||busy} placeholder="Unchanged" onInput={e=>{const next={...values,[field]:e.currentTarget.value};setValues(next);edit(name,next);}} /></div>)}</details>
 <button className="settings-panel__button" type="button" disabled={busy||state.loading||!name||!!error} onClick={()=>void controller.current?.preview()}>Preview server change</button>
 <button className="settings-panel__button" type="button" disabled={busy||state.loading||!name} onClick={()=>{setAck(false);controller.current?.edit({name,action:'update',patch:{disabled:true}});void controller.current?.preview();}}>Preview disable</button>
 <button className="settings-panel__button" type="button" disabled={busy||state.loading||!name||!state.payload?.servers.find(row=>row.name===name)?.localOverride} onClick={()=>{setAck(false);controller.current?.edit({name,action:'remove_override',patch:{}});void controller.current?.preview();}}>Preview remove local override</button>
 {state.previewed&&state.payload?.preview&&<div><p role="status">Preview only: {state.payload.preview.name} — {state.payload.preview.present?(state.payload.preview.enabled?'enabled':'disabled'):'removed'}. {state.payload.preview.action==='remove_override'?'Removing the override may reveal an inherited server.':''}</p><pre aria-label="Effective server preview">{JSON.stringify(state.payload.preview.patch,null,2)}</pre></div>}
 <label><input type="checkbox" checked={ack} disabled={busy||state.loading} onChange={e=>setAck(e.currentTarget.checked)} /> I understand server Apply interrupts turns and reloads extensions.</label>
 <button className="settings-panel__button" type="button" disabled={busy||state.loading||!ack||!state.previewed||!state.payload?.applyAvailable} onClick={()=>void controller.current?.apply(ack)}>{state.applying?'Applying servers…':'Apply server change'}</button>{state.applied&&<p role="status">Server configuration saved and applied to current and new sessions.</p>}</section>;
}
