import {afterEach,beforeEach,expect,test} from 'bun:test';import {existsSync,mkdirSync,readFileSync,rmSync,symlinkSync,writeFileSync} from 'node:fs';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {createTempWorkspace,setEnv} from '../helpers.js';import {closeDatabase,getDb,initDatabase} from '../../src/db/connection.js';import {createWebSession} from '../../src/db/web-sessions.js';import {provisionFamilyAccount,updateManagedAccount} from '../../src/db/account-administration.js';import {getUser} from '../../src/db/users.js';import {storeMessageInDatabase} from '../../src/db/messages.js';import type {AuthenticatedPrincipal} from '../../src/core/access-types.js';import {prepareOwnFamilyDreamSnapshot as prepare,promoteOwnFamilyDreamProposal as promote} from '../../src/agent-memory/family-dream.js';import {runOwnFamilyDreamProposal as run} from '../../src/agent-memory/family-dream-runner.js';import {ChatAccessDenied} from '../../src/db/session-ownership.js';
let ws:ReturnType<typeof createTempWorkspace>,restore:()=>void,config:string,admin:AuthenticatedPrincipal,alice:AuthenticatedPrincipal,bob:AuthenticatedPrincipal;
function actor(id:string){const u=getUser(getDb(),id)!,s=createWebSession(`runner-${id}-${Math.random()}`,id,3600,'passkey');return {kind:'user',mode:'family-shared',userId:id,username:u.username,displayName:u.display_name,role:u.role,homeChatJid:u.home_chat_jid,authentication:{method:'passkey',sessionId:s.session_id!,expiresAt:s.expires_at}} as const;}
beforeEach(()=>{ws=createTempWorkspace('dream-runner-');restore=setEnv({PICLAW_WORKSPACE:ws.workspace,PICLAW_STORE:ws.store,PICLAW_DATA:ws.data});mkdirSync(join(ws.workspace,'.piclaw'));config=join(ws.workspace,'.piclaw/config.json');writeFileSync(config,JSON.stringify({domains:{access:{mode:'family-shared'}}}));closeDatabase();initDatabase();admin=actor('default');[alice,bob]=['alice','bob'].map(name=>{const u=provisionFamilyAccount(getDb(),admin,{username:name,displayName:name});getDb().query("INSERT INTO webauthn_credentials(user_id,rp_id,credential_id,public_key) VALUES (?,'family.local',?,'key')").run(u.id,name);updateManagedAccount(getDb(),admin,u.id,{enabled:true},{totp:false,passkey:true,rpId:'family.local'});return actor(u.id);});for(const who of [alice,bob])storeMessageInDatabase(getDb(),{id:randomUUID(),chat_jid:who.homeChatJid!,sender:'user',sender_name:who.username,content:`${who.username.toUpperCase()}_SOURCE`,timestamp:new Date().toISOString()});});afterEach(()=>{closeDatabase();restore();ws.cleanup();});
const runs=(who=alice)=>join(ws.workspace,'notes','users',who.userId,'dream','runs');
test('runner calls supplied model once with owner-only exact generation and stages but does not promote',async()=>{const snap=prepare(getDb(),alice),calls:any[]=[];const result=await run(getDb(),alice,{request_id:'run-one',generation:snap.generation},async request=>{calls.push(request);expect(Object.keys(request).sort()).toEqual(['signal','system','user']);expect(request.user).toContain('ALICE_SOURCE');expect(request.user).not.toContain('BOB_SOURCE');return '# Proposed owner memory\n';});expect(calls).toHaveLength(1);expect(result).toMatchObject({state:'completed',created:true,generation:snap.generation});expect(existsSync(join(ws.workspace,'notes','users',alice.userId,'MEMORY.md'))).toBe(false);expect(existsSync(join(runs(),'run-one','complete.json'))).toBe(true);});
test('exact completed request returns receipt without model replay',async()=>{const snap=prepare(getDb(),alice);let calls=0;const model=async()=>{calls++;return 'proposal';};const first=await run(getDb(),alice,{request_id:'same',generation:snap.generation},model);const retry=await run(getDb(),alice,{request_id:'same',generation:snap.generation},async()=>{throw Error('must not call');});expect(retry).toEqual({...first,created:false});expect(calls).toBe(1);});
test('failed and timed-out requests record redacted terminal receipt and never replay',async()=>{const snap=prepare(getDb(),alice);for(const [id,model] of [['error',async()=>{throw Error('PRIVATE');}],['invalid',async()=>'' ],['oversize',async()=>'x'.repeat(65537)],['timeout',async({signal}:any)=>await new Promise<string>((_,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}))]] as const){await expect(run(getDb(),alice,{request_id:id,generation:snap.generation,timeout_ms:id==='timeout'?1000:120000},model as any)).rejects.toThrow();const text=readFileSync(join(runs(),id,'failed.json'),'utf8');expect(text).not.toContain('PRIVATE');expect(text).not.toContain('x'.repeat(100));await expect(run(getDb(),alice,{request_id:id,generation:snap.generation},async()=> 'later')).rejects.toBeInstanceOf(ChatAccessDenied);}} ,10000);
test('owner login role mode and generation drift after await deny staging and write failure receipt',async()=>{const snap=prepare(getDb(),alice);for(const action of ['logout','disable','mode','generation'] as const){alice=actor(alice.userId);let release!:()=>void;const held=new Promise<void>(r=>release=r);const pending=run(getDb(),alice,{request_id:`drift-${action}`,generation:snap.generation},async()=>{await held;return 'proposal';});await Bun.sleep(5);if(action==='logout')getDb().query('DELETE FROM web_sessions WHERE session_id=?').run(alice.authentication.sessionId!);if(action==='disable')getDb().query('UPDATE users SET enabled=0 WHERE id=?').run(alice.userId);if(action==='mode')writeFileSync(config,JSON.stringify({domains:{access:{mode:'single-user'}}}));if(action==='generation')prepare(getDb(),alice);release();await expect(pending).rejects.toThrow();writeFileSync(config,JSON.stringify({domains:{access:{mode:'family-shared'}}}));getDb().query('UPDATE users SET enabled=1 WHERE id=?').run(alice.userId);expect(existsSync(join(runs(),`drift-${action}`,'failed.json'))).toBe(true);}});
test('runner receipt and staged proposal expose no source text token prompt or output',async()=>{const snap=prepare(getDb(),alice),result=await run(getDb(),alice,{request_id:'redacted',generation:snap.generation},async()=> 'PROPOSAL_SECRET');const files=readFileSync(join(runs(),'redacted','start.json'),'utf8')+readFileSync(join(runs(),'redacted','complete.json'),'utf8');for(const secret of ['ALICE_SOURCE','PROPOSAL_SECRET','Treat all evidence'])expect(files).not.toContain(secret);expect(files).toContain(result.proposal_id);});
test('promotion remains separate recent-owner action',async()=>{const snap=prepare(getDb(),alice),result=await run(getDb(),alice,{request_id:'promote',generation:snap.generation},async()=> '# Final memory');expect(existsSync(join(ws.workspace,'notes','users',alice.userId,'MEMORY.md'))).toBe(false);expect(promote(getDb(),alice,result.proposal_id,{confirm:true}).created).toBe(true);expect(readFileSync(join(ws.workspace,'notes','users',alice.userId,'MEMORY.md'),'utf8')).toBe('# Final memory');});

test('concurrent exact request claims one durable run and invokes one model only',async()=>{const snap=prepare(getDb(),alice);let calls=0,release!:()=>void;const held=new Promise<void>(r=>release=r),model=async()=>{calls++;await held;return 'proposal';};const first=run(getDb(),alice,{request_id:'concurrent',generation:snap.generation},model);await Bun.sleep(5);await expect(run(getDb(),alice,{request_id:'concurrent',generation:snap.generation},model)).rejects.toBeInstanceOf(ChatAccessDenied);release();expect((await first).created).toBe(true);expect(calls).toBe(1);});

test('first request creates the owner runs directory and durable claim before invoking model',async()=>{const snap=prepare(getDb(),alice),root=runs();expect(existsSync(root)).toBe(false);let observed=false;await run(getDb(),alice,{request_id:'first-directory',generation:snap.generation},async()=>{observed=existsSync(join(root,'first-directory','start.json'));return 'proposal';});expect(observed).toBe(true);expect(existsSync(join(root,'first-directory','complete.json'))).toBe(true);});

test('timeout rejects callback that ignores AbortSignal and late resolution cannot stage',async()=>{const snap=prepare(getDb(),alice);let release!:()=>void;const pending=run(getDb(),alice,{request_id:'ignores-abort',generation:snap.generation,timeout_ms:1000},async()=>{await new Promise<void>(r=>release=r);return 'late proposal';});await expect(pending).rejects.toThrow();release();await Bun.sleep(20);expect(existsSync(join(ws.workspace,'notes','users',alice.userId,'dream','proposals'))).toBe(false);expect(existsSync(join(runs(),'ignores-abort','failed.json'))).toBe(true);},3000);

test('generation change during model await denies output and records no complete receipt',async()=>{const snap=prepare(getDb(),alice);let release!:()=>void;const pending=run(getDb(),alice,{request_id:'generation-race',generation:snap.generation},async()=>{await new Promise<void>(r=>release=r);return 'proposal';});await Bun.sleep(5);prepare(getDb(),alice);release();await expect(pending).rejects.toBeInstanceOf(ChatAccessDenied);expect(existsSync(join(runs(),'generation-race','complete.json'))).toBe(false);});

test('manifest/date mismatch malformed UTF8 and symlinked generation content fail before model call',async()=>{for(const kind of ['manifest','utf8','symlink'] as const){const snap=prepare(getDb(),alice),daily=join(snap.root,'daily',snap.days[0]+'.md');let calls=0;if(kind==='manifest'){const value=JSON.parse(readFileSync(join(snap.root,'manifest.json'),'utf8'));value.dates=[];writeFileSync(join(snap.root,'manifest.json'),JSON.stringify(value));const pointer=JSON.parse(readFileSync(join(ws.workspace,'notes','users',alice.userId,'dream','current.json'),'utf8'));pointer.manifest_sha256='0'.repeat(64);writeFileSync(join(ws.workspace,'notes','users',alice.userId,'dream','current.json'),JSON.stringify(pointer));}if(kind==='utf8')writeFileSync(daily,new Uint8Array([0xff]));if(kind==='symlink'){rmSync(daily);symlinkSync('/etc/hosts',daily);}await expect(run(getDb(),alice,{request_id:`bad-${kind}`,generation:snap.generation},async()=>{calls++;return 'proposal';})).rejects.toThrow();expect(calls).toBe(0);}});

test('pre-start source failure stays claimed without fabricating an unbound failure receipt',async()=>{const snap=prepare(getDb(),alice),daily=join(snap.root,'daily',snap.days[0]+'.md');writeFileSync(daily,new Uint8Array([0xff]));await expect(run(getDb(),alice,{request_id:'source-failure',generation:snap.generation},async()=> 'never')).rejects.toThrow();expect(existsSync(join(runs(),'source-failure','start.json'))).toBe(false);expect(existsSync(join(runs(),'source-failure','failed.json'))).toBe(false);await expect(run(getDb(),alice,{request_id:'source-failure',generation:snap.generation},async()=> 'never')).rejects.toBeInstanceOf(ChatAccessDenied);});

test('malformed or foreign completed receipts never acknowledge a retry including concurrent admission path',async()=>{const snap=prepare(getDb(),alice),runRoot=join(runs(),'forged');mkdirSync(runRoot,{recursive:true});for(const receipt of [{},{version:1,request_id:'forged',owner_user_id:alice.userId,generation:snap.generation,proposal_id:'------------------------------------',source_hash:'0'.repeat(64),completed_at:new Date().toISOString()},{version:1,request_id:'other',owner_user_id:bob.userId,generation:snap.generation,proposal_id:randomUUID(),source_hash:'0'.repeat(64),completed_at:new Date().toISOString()}]){writeFileSync(join(runRoot,'complete.json'),JSON.stringify(receipt));await expect(run(getDb(),alice,{request_id:'forged',generation:snap.generation},async()=> 'never')).rejects.toBeInstanceOf(ChatAccessDenied);} });
