import {afterEach,beforeEach,expect,test} from 'bun:test';
import {mkdirSync,readFileSync,writeFileSync,existsSync,rmSync} from 'node:fs';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {createTempWorkspace,setEnv} from '../helpers.js';import {closeDatabase,getDb,initDatabase} from '../../src/db/connection.js';
import {createWebSession} from '../../src/db/web-sessions.js';import {provisionFamilyAccount,updateManagedAccount} from '../../src/db/account-administration.js';import {getUser} from '../../src/db/users.js';
import {createOwnedRoot,archiveOwnedSession} from '../../src/db/owned-session-lifecycle.js';import {storeMessageInDatabase} from '../../src/db/messages.js';import type {AuthenticatedPrincipal} from '../../src/core/access-types.js';
import {prepareOwnFamilyDreamSnapshot as prepare} from '../../src/agent-memory/family-dream.js';import {withExecutionIdentity} from '../../src/core/execution-context.js';import {ChatAccessDenied} from '../../src/db/session-ownership.js';
let ws:ReturnType<typeof createTempWorkspace>,restore:()=>void,config:string,admin:AuthenticatedPrincipal,alice:AuthenticatedPrincipal,bob:AuthenticatedPrincipal;
function actor(id:string){const u=getUser(getDb(),id)!,s=createWebSession(`dream-${id}-${Math.random()}`,id,3600,'passkey');return {kind:'user',mode:'family-shared',userId:id,username:u.username,displayName:u.display_name,role:u.role,homeChatJid:u.home_chat_jid,authentication:{method:'passkey',sessionId:s.session_id!,expiresAt:s.expires_at}} as const;}
beforeEach(()=>{ws=createTempWorkspace('family-dream-');restore=setEnv({PICLAW_WORKSPACE:ws.workspace,PICLAW_STORE:ws.store,PICLAW_DATA:ws.data});mkdirSync(join(ws.workspace,'.piclaw'));config=join(ws.workspace,'.piclaw/config.json');writeFileSync(config,JSON.stringify({domains:{access:{mode:'family-shared'}}}));closeDatabase();initDatabase();admin=actor('default');[alice,bob]=['alice','bob'].map(name=>{const u=provisionFamilyAccount(getDb(),admin,{username:name,displayName:name});getDb().query("INSERT INTO webauthn_credentials(user_id,rp_id,credential_id,public_key) VALUES (?,'family.local',?,'key')").run(u.id,name);updateManagedAccount(getDb(),admin,u.id,{enabled:true},{totp:false,passkey:true,rpId:'family.local'});return actor(u.id);});});
afterEach(()=>{closeDatabase();restore();ws.cleanup();});
function message(who:AuthenticatedPrincipal,text:string,chat=who.homeChatJid!,timestamp=new Date().toISOString()){return storeMessageInDatabase(getDb(),{id:randomUUID(),chat_jid:chat,sender:'user',sender_name:who.username,content:text,timestamp});}
function current(who=alice){const root=join(ws.workspace,'notes','users',who.userId,'dream'),pointer=JSON.parse(readFileSync(join(root,'current.json'),'utf8'));return {root,pointer,generation:join(root,'generations',pointer.generation)};}

test('snapshot contains all and only one owner session trees with fixed private output root',()=>{const a2=createOwnedRoot(getDb(),alice,'alice-two'),b2=createOwnedRoot(getDb(),bob,'bob-two');message(alice,'ALICE_HOME');message(alice,'ALICE_CHILD',a2.chat_jid);message(bob,'BOB_HOME');message(bob,'BOB_CHILD',b2.chat_jid);message(alice,'DREAM_INTERNAL','dream:manual:test');archiveOwnedSession(getDb(),alice,a2.chat_jid);
  const out=prepare(getDb(),alice,{days:7}),saved=current(),all=readFileSync(join(saved.generation,'daily',out.days[0]+'.md'),'utf8');expect(out).toMatchObject({owner_user_id:alice.userId,message_count:2,tree_count:2});expect(all).toContain('ALICE_HOME');expect(all).toContain('ALICE_CHILD');for(const secret of ['BOB_HOME','BOB_CHILD','DREAM_INTERNAL',bob.userId])expect(all).not.toContain(secret);expect(saved.generation).toBe(out.root);expect(saved.pointer.owner_user_id).toBe(alice.userId);expect(out.root.startsWith(join(ws.workspace,'notes','users',alice.userId,'dream','generations'))).toBe(true);});

test('different owners have independent locks and generations while same-owner lock fails closed',()=>{message(alice,'A');message(bob,'B');const root=join(ws.workspace,'notes','users',alice.userId,'dream');mkdirSync(root,{recursive:true});writeFileSync(join(root,'.lock'),'held');expect(()=>prepare(getDb(),alice)).toThrow();expect(prepare(getDb(),bob).message_count).toBe(1);expect(existsSync(join(root,'current.json'))).toBe(false);rmSync(join(root,'.lock'));expect(prepare(getDb(),alice).message_count).toBe(1);});

test('new generation atomically advances current pointer and leaves prior immutable generation',async()=>{message(alice,'FIRST');const first=prepare(getDb(),alice);await Bun.sleep(2);message(alice,'SECOND');const second=prepare(getDb(),alice);expect(second.generation).not.toBe(first.generation);expect(existsSync(first.root)).toBe(true);expect(readFileSync(join(first.root,'MEMORY.md'),'utf8')).not.toContain('SECOND');expect(readFileSync(join(second.root,'daily',second.days[0]+'.md'),'utf8')).toContain('SECOND');expect(current().pointer.generation).toBe(second.generation);});

test('invalid authority mode limits and execution contexts deny before writes',()=>{message(alice,'A');const root=join(ws.workspace,'notes','users',alice.userId,'dream');for(const days of [0,32,1.5,NaN])expect(()=>prepare(getDb(),alice,{days})).toThrow(ChatAccessDenied);for(const who of [bob,admin]){const forged={...who,userId:alice.userId};expect(()=>prepare(getDb(),forged as any)).toThrow(ChatAccessDenied);}for(const mode of ['single-user','isolated-containers','invalid']){writeFileSync(config,mode==='invalid'?'{':JSON.stringify({domains:{access:{mode}}}));expect(()=>prepare(getDb(),alice)).toThrow();}writeFileSync(config,JSON.stringify({domains:{access:{mode:'family-shared'}}}));expect(()=>withExecutionIdentity({mode:'family-shared'} as any,()=>prepare(getDb(),alice))).toThrow();expect(existsSync(join(root,'current.json'))).toBe(false);});

test('revoked old and wrong-factor logins deny and no other owner can observe output path through result',()=>{message(alice,'SECRET');getDb().query('UPDATE web_sessions SET created_at=? WHERE session_id=?').run(new Date(Date.now()-600000).toISOString(),alice.authentication.sessionId!);expect(()=>prepare(getDb(),alice)).toThrow();alice=actor(alice.userId);getDb().query("UPDATE web_sessions SET auth_method='password' WHERE session_id=?").run(alice.authentication.sessionId!);expect(()=>prepare(getDb(),alice)).toThrow();alice=actor(alice.userId);getDb().query('DELETE FROM web_sessions WHERE session_id=?').run(alice.authentication.sessionId!);expect(()=>prepare(getDb(),alice)).toThrow();});

test('message count content and malformed row bounds fail without advancing current',()=>{const first=prepare(getDb(),alice);const before=current().pointer.generation;getDb().query("INSERT INTO messages(id,chat_jid,sender,sender_name,content,timestamp) VALUES ('large',?,'user','a',?,?)").run(alice.homeChatJid,'x'.repeat(102401),new Date().toISOString());expect(()=>prepare(getDb(),actor(alice.userId))).toThrow();expect(current().pointer.generation).toBe(before);expect(first.message_count).toBe(0);});

test('oversized emitted metadata is rejected without advancing current pointer',()=>{const first=prepare(getDb(),alice),before=current().pointer.generation;getDb().query("INSERT INTO messages(id,chat_jid,sender,sender_name,content,timestamp) VALUES ('wide-name',?,'user',?,'text',?)").run(alice.homeChatJid,'é'.repeat(300),new Date().toISOString());expect(()=>prepare(getDb(),actor(alice.userId))).toThrow(ChatAccessDenied);expect(current().pointer.generation).toBe(before);expect(first.message_count).toBe(0);});

test('staging failure preserves current pointer and cleans only its stage',()=>{message(alice,'A');const first=prepare(getDb(),alice),root=current().root;mkdirSync(join(root,'.stage-blocked'),{recursive:true});writeFileSync(join(root,'.lock'),'someone');expect(()=>prepare(getDb(),alice)).toThrow();expect(current().pointer.generation).toBe(first.generation);expect(existsSync(join(root,'.stage-blocked'))).toBe(true);rmSync(join(root,'.lock'));});

test('scope never imports legacy daily/memory or another user output',()=>{mkdirSync(join(ws.workspace,'notes'),{recursive:true});writeFileSync(join(ws.workspace,'notes','daily-legacy'),'LEGACY');mkdirSync(join(ws.workspace,'notes','users',bob.userId,'dream'),{recursive:true});writeFileSync(join(ws.workspace,'notes','users',bob.userId,'dream','private'),'BOB_OUTPUT');message(alice,'ONLY_ALICE');const out=prepare(getDb(),alice),files=JSON.stringify([readFileSync(join(out.root,'MEMORY.md'),'utf8'),...out.days.map(d=>readFileSync(join(out.root,'daily',d+'.md'),'utf8'))]);expect(files).toContain('ONLY_ALICE');expect(files).not.toContain('LEGACY');expect(files).not.toContain('BOB_OUTPUT');});

test('non-dream child below an owned dream root is excluded by authoritative root identity',()=>{const db=getDb(),now=new Date().toISOString(),root='dream:owner-fixture',child='web:ordinary-looking-child';
  db.query("INSERT INTO chats(jid,name,last_message_time) VALUES (?,?,'')").run(root,root);db.query("INSERT INTO chats(jid,name,last_message_time) VALUES (?,?,'')").run(child,child);
  db.query("INSERT INTO chat_branches(branch_id,chat_jid,root_chat_jid,parent_branch_id,agent_name,created_at,updated_at) VALUES ('dream-root',?,?,NULL,'dream',?,?)").run(root,root,now,now);
  db.query("INSERT INTO chat_branches(branch_id,chat_jid,root_chat_jid,parent_branch_id,agent_name,created_at,updated_at) VALUES ('dream-child',?,?,'dream-root','child',?,?)").run(child,root,now,now);
  db.query("INSERT INTO session_roots(root_branch_id,owner_user_id,policy,created_at) VALUES ('dream-root',?,'private',?)").run(alice.userId,now);
  message(alice,'RECURSIVE_DREAM_CONTENT',child);message(alice,'REAL_CONTENT');const out=prepare(db,alice),text=out.days.map(d=>readFileSync(join(out.root,'daily',d+'.md'),'utf8')).join('\n');expect(text).toContain('REAL_CONTENT');expect(text).not.toContain('RECURSIVE_DREAM_CONTENT');expect(out.message_count).toBe(1);
});
