import {afterEach,beforeEach,expect,test} from 'bun:test';import {mkdirSync,readFileSync,rmSync,writeFileSync,existsSync} from 'node:fs';import {join} from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import {createTempWorkspace,setEnv} from '../helpers.js';import {closeDatabase,getDb,initDatabase} from '../../src/db/connection.js';import {createWebSession} from '../../src/db/web-sessions.js';import {provisionFamilyAccount,updateManagedAccount} from '../../src/db/account-administration.js';import {getUser} from '../../src/db/users.js';import {storeMessageInDatabase} from '../../src/db/messages.js';import type {AuthenticatedPrincipal} from '../../src/core/access-types.js';
import {prepareOwnFamilyDreamSnapshot as prepare,issueOwnFamilyDreamProposalCapability as issue,stageFamilyDreamProposal as stage} from '../../src/agent-memory/family-dream.js';import {recoverOwnFamilyDreamRun as recover,runOwnFamilyDreamProposal as run} from '../../src/agent-memory/family-dream-runner.js';import {ChatAccessDenied} from '../../src/db/session-ownership.js';
let ws:ReturnType<typeof createTempWorkspace>,restore:()=>void,config:string,admin:AuthenticatedPrincipal,alice:AuthenticatedPrincipal,bob:AuthenticatedPrincipal;
function actor(id:string){const u=getUser(getDb(),id)!,s=createWebSession(`recover-${id}-${Math.random()}`,id,3600,'passkey');return {kind:'user',mode:'family-shared',userId:id,username:u.username,displayName:u.display_name,role:u.role,homeChatJid:u.home_chat_jid,authentication:{method:'passkey',sessionId:s.session_id!,expiresAt:s.expires_at}} as const;}
beforeEach(()=>{ws=createTempWorkspace('dream-recovery-');restore=setEnv({PICLAW_WORKSPACE:ws.workspace,PICLAW_STORE:ws.store,PICLAW_DATA:ws.data});mkdirSync(join(ws.workspace,'.piclaw'));config=join(ws.workspace,'.piclaw/config.json');writeFileSync(config,JSON.stringify({domains:{access:{mode:'family-shared'}}}));closeDatabase();initDatabase();admin=actor('default');[alice,bob]=['alice','bob'].map(name=>{const u=provisionFamilyAccount(getDb(),admin,{username:name,displayName:name});getDb().query("INSERT INTO webauthn_credentials(user_id,rp_id,credential_id,public_key) VALUES (?,'family.local',?,'key')").run(u.id,name);updateManagedAccount(getDb(),admin,u.id,{enabled:true},{totp:false,passkey:true,rpId:'family.local'});return actor(u.id);});storeMessageInDatabase(getDb(),{id:randomUUID(),chat_jid:alice.homeChatJid!,sender:'user',sender_name:'alice',content:'source',timestamp:new Date().toISOString()});});afterEach(()=>{closeDatabase();restore();ws.cleanup();});
const ownerRoot=()=>join(ws.workspace,'notes','users',alice.userId,'dream');const runRoot=(id:string)=>join(ownerRoot(),'runs',id);const digest=(v:string)=>createHash('sha256').update(v).digest('hex');
function start(id:string,generation:string,proposalId=randomUUID(),recoverAfter=new Date(Date.now()-1).toISOString()){const root=runRoot(id);mkdirSync(root,{recursive:true});writeFileSync(join(root,'start.json'),JSON.stringify({version:1,request_id:id,owner_user_id:alice.userId,generation,proposal_id:proposalId,source_hash:'0'.repeat(64),started_at:new Date(Date.now()-120000).toISOString(),recover_after:recoverAfter}));return {root,proposalId};}

test('stale started run without proposal becomes immutable redacted failure and never runs model',async()=>{const snap=prepare(getDb(),alice),s=start('stale',snap.generation);const first=recover(getDb(),alice,'stale',{confirm:true});expect(first).toEqual({request_id:'stale',state:'failed',created:true});expect(recover(getDb(),alice,'stale',{confirm:true})).toEqual({...first,created:false});const text=readFileSync(join(s.root,'failed.json'),'utf8');expect(text).not.toContain('PRIVATE_SOURCE_TEXT');expect(Object.keys(JSON.parse(text)).sort()).toEqual(['failed_at','generation','owner_user_id','request_id','source_hash','version']);let calls=0;await expect(run(getDb(),alice,{request_id:'stale',generation:snap.generation},async()=>{calls++;return 'x';})).rejects.toBeInstanceOf(ChatAccessDenied);expect(calls).toBe(0);});

test('stale run with exact fully staged proposal reconciles completion without model or promotion',()=>{const snap=prepare(getDb(),alice),cap=issue(getDb(),alice),s=start('reconcile',snap.generation,cap.proposal_id);stage(getDb(),cap,'proposal',{run_request_id:'reconcile'});const out=recover(getDb(),alice,'reconcile',{confirm:true});expect(out).toMatchObject({request_id:'reconcile',generation:snap.generation,proposal_id:cap.proposal_id,state:'completed',created:true});expect(existsSync(join(s.root,'complete.json'))).toBe(true);expect(existsSync(join(ws.workspace,'notes','users',alice.userId,'MEMORY.md'))).toBe(false);expect(recover(getDb(),alice,'reconcile',{confirm:true})).toMatchObject({state:'completed',created:false});});

test('recovery denies before deadline, active in-process run and foreign or stale owner',async()=>{const snap=prepare(getDb(),alice),future=start('future',snap.generation,randomUUID(),new Date(Date.now()+60000).toISOString());expect(()=>recover(getDb(),alice,'future',{confirm:true})).toThrow(ChatAccessDenied);let release!:()=>void;const pending=run(getDb(),alice,{request_id:'active',generation:snap.generation},async()=>{await new Promise<void>(r=>release=r);return 'proposal';});await Bun.sleep(5);expect(()=>recover(getDb(),alice,'active',{confirm:true},Date.now()+999999)).toThrow(ChatAccessDenied);release();await pending;expect(()=>recover(getDb(),bob,'future',{confirm:true},Date.now()+999999)).toThrow(ChatAccessDenied);getDb().query('DELETE FROM web_sessions WHERE session_id=?').run(alice.authentication.sessionId!);expect(()=>recover(getDb(),alice,'future',{confirm:true},Date.now()+999999)).toThrow(ChatAccessDenied);expect(existsSync(join(future.root,'failed.json'))).toBe(false);});

test('malformed receipts and proposal mismatches fail closed without terminalising',()=>{const snap=prepare(getDb(),alice);for(const [id,mutation] of [['shape',()=>writeFileSync(join(runRoot('shape'),'start.json'),'{}')],['proposal',()=>{const cap=issue(getDb(),alice),s=start('proposal',snap.generation,cap.proposal_id);stage(getDb(),cap,'body',{run_request_id:'other'});return s;}]] as const){const s=id==='shape'?(start(id,snap.generation),{root:runRoot(id)}):mutation()!;if(id==='shape')mutation();expect(()=>recover(getDb(),alice,id,{confirm:true},Date.now()+999999)).toThrow(ChatAccessDenied);expect(existsSync(join(s.root,'failed.json'))).toBe(false);}});

test('mode confirmation and lock constraints deny without model proposal or promotion effects',()=>{const snap=prepare(getDb(),alice),s=start('locked',snap.generation),lock=join(ownerRoot(),'.lock');writeFileSync(lock,'held');expect(()=>recover(getDb(),alice,'locked',{confirm:true})).toThrow();rmSync(lock);for(const input of [{confirm:false},{confirm:true,extra:1},{}])expect(()=>recover(getDb(),alice,'locked',input as any)).toThrow(ChatAccessDenied);writeFileSync(config,JSON.stringify({domains:{access:{mode:'single-user'}}}));expect(()=>recover(getDb(),alice,'locked',{confirm:true})).toThrow();expect(existsSync(join(s.root,'failed.json'))).toBe(false);});

test('completed receipts are strictly acknowledged without touching failed state',async()=>{const snap=prepare(getDb(),alice),out=await run(getDb(),alice,{request_id:'done',generation:snap.generation},async()=> 'proposal');const retry=recover(getDb(),alice,'done',{confirm:true},Date.now()+999999);expect(retry).toEqual({...out,created:false});expect(existsSync(join(runRoot('done'),'failed.json'))).toBe(false);const value=JSON.parse(readFileSync(join(runRoot('done'),'complete.json'),'utf8'));value.owner_user_id=bob.userId;writeFileSync(join(runRoot('done'),'complete.json'),JSON.stringify(value));expect(()=>recover(getDb(),alice,'done',{confirm:true},Date.now()+999999)).toThrow(ChatAccessDenied);});

test('runner failure defers terminalisation while owner lock is held and recovery later creates one terminal',async()=>{const snap=prepare(getDb(),alice),lock=join(ownerRoot(),'.lock');let release!:()=>void;const pending=run(getDb(),alice,{request_id:'failure-lock',generation:snap.generation},async()=>{writeFileSync(lock,'other process');await new Promise<void>(r=>release=r);throw Error('model failed');});await Bun.sleep(5);release();await expect(pending).rejects.toThrow();expect(existsSync(join(runRoot('failure-lock'),'failed.json'))).toBe(false);rmSync(lock);expect(recover(getDb(),alice,'failure-lock',{confirm:true},Date.now()+999999)).toEqual({request_id:'failure-lock',state:'failed',created:true});expect(existsSync(join(runRoot('failure-lock'),'complete.json'))).toBe(false);});

test('malformed failed receipt and start-completion mismatch never acknowledge terminal state',async()=>{const snap=prepare(getDb(),alice),s=start('bad-failed',snap.generation);writeFileSync(join(s.root,'failed.json'),'{}');expect(()=>recover(getDb(),alice,'bad-failed',{confirm:true},Date.now()+999999)).toThrow(ChatAccessDenied);const out=await run(getDb(),alice,{request_id:'bad-complete',generation:snap.generation},async()=> 'proposal'),root=runRoot('bad-complete'),startValue=JSON.parse(readFileSync(join(root,'start.json'),'utf8'));startValue.proposal_id=randomUUID();writeFileSync(join(root,'start.json'),JSON.stringify(startValue));expect(()=>recover(getDb(),alice,'bad-complete',{confirm:true},Date.now()+999999)).toThrow(ChatAccessDenied);expect(out.state).toBe('completed');});
