import {afterEach,beforeEach,expect,test} from 'bun:test';import {existsSync,mkdirSync,readFileSync,rmSync,writeFileSync} from 'node:fs';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {createTempWorkspace,setEnv} from '../helpers.js';import {closeDatabase,getDb,initDatabase} from '../../src/db/connection.js';import {createWebSession} from '../../src/db/web-sessions.js';import {provisionFamilyAccount,updateManagedAccount} from '../../src/db/account-administration.js';import {getUser} from '../../src/db/users.js';import {storeMessageInDatabase} from '../../src/db/messages.js';import type {AuthenticatedPrincipal} from '../../src/core/access-types.js';
import {prepareOwnFamilyDreamSnapshot as prepare,issueOwnFamilyDreamProposalCapability as issue,stageFamilyDreamProposal as stage,promoteOwnFamilyDreamProposal as promote} from '../../src/agent-memory/family-dream.js';import {ChatAccessDenied} from '../../src/db/session-ownership.js';
let ws:ReturnType<typeof createTempWorkspace>,restore:()=>void,config:string,admin:AuthenticatedPrincipal,alice:AuthenticatedPrincipal,bob:AuthenticatedPrincipal;
function actor(id:string){const u=getUser(getDb(),id)!,s=createWebSession(`promotion-${id}-${Math.random()}`,id,3600,'passkey');return {kind:'user',mode:'family-shared',userId:id,username:u.username,displayName:u.display_name,role:u.role,homeChatJid:u.home_chat_jid,authentication:{method:'passkey',sessionId:s.session_id!,expiresAt:s.expires_at}} as const;}
beforeEach(()=>{ws=createTempWorkspace('dream-promotion-');restore=setEnv({PICLAW_WORKSPACE:ws.workspace,PICLAW_STORE:ws.store,PICLAW_DATA:ws.data});mkdirSync(join(ws.workspace,'.piclaw'));config=join(ws.workspace,'.piclaw/config.json');writeFileSync(config,JSON.stringify({domains:{access:{mode:'family-shared'}}}));closeDatabase();initDatabase();admin=actor('default');[alice,bob]=['alice','bob'].map(name=>{const u=provisionFamilyAccount(getDb(),admin,{username:name,displayName:name});getDb().query("INSERT INTO webauthn_credentials(user_id,rp_id,credential_id,public_key) VALUES (?,'family.local',?,'key')").run(u.id,name);updateManagedAccount(getDb(),admin,u.id,{enabled:true},{totp:false,passkey:true,rpId:'family.local'});return actor(u.id);});for(const who of [alice,bob])storeMessageInDatabase(getDb(),{id:randomUUID(),chat_jid:who.homeChatJid!,sender:'user',sender_name:who.username,content:`${who.username} source`,timestamp:new Date().toISOString()});});
afterEach(()=>{closeDatabase();restore();ws.cleanup();});
const memory=(who=alice)=>join(ws.workspace,'notes','users',who.userId,'MEMORY.md');
function proposal(who=alice,text='# Owner memory\n\n- durable\n'){prepare(getDb(),who);const cap=issue(getDb(),who);return {...stage(getDb(),cap,text),cap,text};}

test('private one-use capability stages bounded proposal without writing personal memory',()=>{prepare(getDb(),alice);const cap=issue(getDb(),alice),before=JSON.stringify(cap);const result=stage(getDb(),cap,'# Alice memory\n');expect(result).toMatchObject({owner_user_id:alice.userId,generation:cap.generation,created:true});expect(existsSync(memory())).toBe(false);expect(JSON.stringify(result)).not.toContain(cap.token);expect(()=>stage(getDb(),cap,'# Again')).toThrow();expect(JSON.stringify(cap)).toBe(before);});

test('forged changed expired and wrong-generation capabilities deny without proposal or memory',()=>{prepare(getDb(),alice);const cap=issue(getDb(),alice),root=join(ws.workspace,'notes','users',alice.userId,'dream','proposals',cap.proposal_id);for(const patch of [{token:'x'},{proposal_id:randomUUID()},{generation:'wrong'},{extra:true}])expect(()=>stage(getDb(),{...cap,...patch} as any,'x')).toThrow(ChatAccessDenied);expect(existsSync(root)).toBe(false);prepare(getDb(),alice);expect(()=>stage(getDb(),cap,'x')).toThrow(ChatAccessDenied);expect(existsSync(memory())).toBe(false);});

test('proposal output validates UTF8 NUL and 64KiB and capability remains retryable after invalid text',()=>{prepare(getDb(),alice);for(const value of ['', ' ', '\0', '\ud800','x'.repeat(65537)]){const cap=issue(getDb(),alice);expect(()=>stage(getDb(),cap,value)).toThrow(ChatAccessDenied);expect(stage(getDb(),cap,'valid').created).toBe(true);}expect(existsSync(memory())).toBe(false);});

test('recent owner promotes exact proposal atomically and exact retry verifies receipt and memory hash',()=>{const p=proposal();const first=promote(getDb(),alice,p.proposal_id,{confirm:true});expect(first).toEqual({proposal_id:p.proposal_id,promoted:true,created:true,memory_path:memory()});expect(readFileSync(memory(),'utf8')).toBe(p.text);expect(promote(getDb(),alice,p.proposal_id,{confirm:true})).toEqual({...first,created:false});expect(()=>promote(getDb(),bob,p.proposal_id,{confirm:true})).toThrow(ChatAccessDenied);});

test('base hash prevents overwrite after owner edit and after new generation',()=>{mkdirSync(join(ws.workspace,'notes','users',alice.userId),{recursive:true});writeFileSync(memory(),'base');const p=proposal(alice,'proposal');writeFileSync(memory(),'owner edit');expect(()=>promote(getDb(),alice,p.proposal_id,{confirm:true})).toThrow(ChatAccessDenied);expect(readFileSync(memory(),'utf8')).toBe('owner edit');const q=proposal(alice,'next');prepare(getDb(),alice);expect(()=>promote(getDb(),alice,q.proposal_id,{confirm:true})).toThrow(ChatAccessDenied);});

test('promotion response-gap recovery records receipt only when current memory equals exact output',()=>{const p=proposal(alice,'recovered');const root=join(ws.workspace,'notes','users',alice.userId,'dream','proposals',p.proposal_id);writeFileSync(memory(),'recovered');const value=promote(getDb(),alice,p.proposal_id,{confirm:true});expect(value.created).toBe(true);expect(existsSync(join(root,'promotion.json'))).toBe(true);writeFileSync(memory(),'later edit');expect(()=>promote(getDb(),alice,p.proposal_id,{confirm:true})).toThrow(ChatAccessDenied);});

test('old wrong-factor revoked disabled and malformed confirmation deny promotion',()=>{const p=proposal();for(const input of [{confirm:false},{confirm:true,extra:1},{}])expect(()=>promote(getDb(),alice,p.proposal_id,input as any)).toThrow(ChatAccessDenied);getDb().query('UPDATE web_sessions SET created_at=? WHERE session_id=?').run(new Date(Date.now()-600000).toISOString(),alice.authentication.sessionId!);expect(()=>promote(getDb(),alice,p.proposal_id,{confirm:true})).toThrow(ChatAccessDenied);alice=actor(alice.userId);getDb().query("UPDATE web_sessions SET auth_method='password' WHERE session_id=?").run(alice.authentication.sessionId!);expect(()=>promote(getDb(),alice,p.proposal_id,{confirm:true})).toThrow(ChatAccessDenied);alice=actor(alice.userId);getDb().query('UPDATE users SET enabled=0 WHERE id=?').run(alice.userId);expect(()=>promote(getDb(),alice,p.proposal_id,{confirm:true})).toThrow(ChatAccessDenied);});

test('mode and database changes deny issue stage and promotion without cross-owner effects',()=>{prepare(getDb(),alice);const cap=issue(getDb(),alice);for(const mode of ['single-user','isolated-containers','invalid']){writeFileSync(config,mode==='invalid'?'{':JSON.stringify({domains:{access:{mode}}}));expect(()=>issue(getDb(),alice)).toThrow();expect(()=>stage(getDb(),cap,'text')).toThrow();}writeFileSync(config,JSON.stringify({domains:{access:{mode:'family-shared'}}}));const p=proposal();closeDatabase();initDatabase();expect(()=>promote(getDb(),alice,p.proposal_id,{confirm:true})).toThrow();expect(existsSync(memory(bob))).toBe(false);});

test('proposal and receipt expose no capability and generation source stays immutable',()=>{const p=proposal(),generation=join(ws.workspace,'notes','users',alice.userId,'dream','generations',p.generation),source=readFileSync(join(generation,'MEMORY.md'),'utf8');promote(getDb(),alice,p.proposal_id,{confirm:true});const files=readFileSync(join(ws.workspace,'notes','users',alice.userId,'dream','proposals',p.proposal_id,'proposal.json'),'utf8')+readFileSync(join(ws.workspace,'notes','users',alice.userId,'dream','proposals',p.proposal_id,'promotion.json'),'utf8');expect(files).not.toContain(p.cap.token);expect(readFileSync(join(generation,'MEMORY.md'),'utf8')).toBe(source);expect(existsSync(memory(bob))).toBe(false);});

test('one owner-wide lock serialises generation preparation staging and promotion',()=>{prepare(getDb(),alice);const cap=issue(getDb(),alice),root=join(ws.workspace,'notes','users',alice.userId,'dream'),lock=join(root,'.lock');writeFileSync(lock,'held');expect(()=>stage(getDb(),cap,'proposal')).toThrow();rmSync(lock);const p={...stage(getDb(),cap,'proposal'),cap};writeFileSync(lock,'held');expect(()=>promote(getDb(),alice,p.proposal_id,{confirm:true})).toThrow();expect(existsSync(memory())).toBe(false);rmSync(lock);expect(promote(getDb(),alice,p.proposal_id,{confirm:true}).created).toBe(true);});

test('capability cannot stage after a newer generation is published before it acquires owner lock',()=>{prepare(getDb(),alice);const cap=issue(getDb(),alice);prepare(getDb(),alice);expect(()=>stage(getDb(),cap,'stale proposal')).toThrow(ChatAccessDenied);expect(existsSync(join(ws.workspace,'notes','users',alice.userId,'dream','proposals',cap.proposal_id))).toBe(false);});
