import {html,useEffect,useRef,useState} from '../../vendor/preact-htm.js';
import {createMcpServerSettingsController,INITIAL_MCP_SERVERS,MCP_SERVER_FIELDS,patchFromForm,type McpServerSettingsState} from '../../ui/mcp-server-settings-model.js';
export function McpServersSection({busy=false,onApplying=(_applying:boolean)=>{}}:{busy?:boolean;onApplying?:(applying:boolean)=>void}={}){
 const[state,setState]=useState<McpServerSettingsState>(INITIAL_MCP_SERVERS),[name,setName]=useState(''),[values,setValues]=useState<Record<string,string>>({}),[ack,setAck]=useState(false),[error,setError]=useState('');
 const controller=useRef<ReturnType<typeof createMcpServerSettingsController>|null>(null);
 useEffect(()=>{const current=createMcpServerSettingsController(setState);controller.current=current;void current.refresh();return()=>{current.dispose();controller.current=null;};},[]);
 useEffect(()=>{onApplying(state.applying);},[state.applying]);
 const edit=(nextName:string,nextValues:Record<string,string>)=>{setAck(false);setError('');try{controller.current?.edit({name:nextName,action:'update',patch:patchFromForm(nextValues)});}catch{setError('Use valid JSON for array, object, boolean and numeric fields.');controller.current?.edit({name:nextName,action:'update',patch:{}});}};
 return html`<section class="mcp-server-editor" aria-label="MCP server editor"><h4>Adapter servers</h4><p class="settings-hint">Only the local project override is changed. Blank fields preserve existing values; null removes a local field and may reveal an inherited value. Private arguments/maps and advanced fields are withheld and preserved. Never paste a secret: use environment or keychain references.</p>
 <button class="settings-btn" type="button" disabled=${busy||state.loading} onClick=${()=>void controller.current?.refresh()}>Refresh servers</button>
 ${state.error&&html`<p role="alert" class="settings-error">${state.error}</p>`}${error&&html`<p role="alert" class="settings-error">${error}</p>`}
 ${state.payload&&html`<p class="settings-hint">Server runtime: ${state.payload.phase}. Apply interrupts active turns and reloads extensions across all chats; chat history is retained.</p><ul>${state.payload.servers.map(row=>html`<li><button type="button" disabled=${state.applying||busy} onClick=${()=>{setName(row.name);setValues({});edit(row.name,{});}}>${row.name}</button> — ${row.enabled?'enabled':'disabled'}, ${row.localOverride?'local override':'inherited'}${row.withheldFields.length?` (private/advanced fields preserved: ${row.withheldFields.join(', ')})`:''}</li>`)}</ul>`}
 <label for="mcp-server-name">Server name</label><input id="mcp-server-name" value=${name} disabled=${state.applying||busy} onInput=${(e:Event)=>{const next=(e.target as HTMLInputElement).value;setName(next);edit(next,values);}} />
 <details><summary>Transport, authentication references, exposure and timeouts</summary>${MCP_SERVER_FIELDS.map(([field,label])=>html`<div class="settings-row settings-row-vertical"><label for=${`mcp-server-${field}`}>${label}</label><input id=${`mcp-server-${field}`} value=${values[field]??''} disabled=${state.applying||busy} placeholder="Unchanged" onInput=${(e:Event)=>{const next={...values,[field]:(e.target as HTMLInputElement).value};setValues(next);edit(name,next);}} /></div>`)}</details>
 <button class="settings-btn" type="button" disabled=${busy||state.loading||!name||!!error} onClick=${()=>void controller.current?.preview()}>Preview server change</button>
 <button class="settings-btn" type="button" disabled=${busy||state.loading||!name} onClick=${()=>{setAck(false);controller.current?.edit({name,action:'update',patch:{disabled:true}});void controller.current?.preview();}}>Preview disable</button>
 <button class="settings-btn" type="button" disabled=${busy||state.loading||!name||!state.payload?.servers.find(row=>row.name===name)?.localOverride} onClick=${()=>{setAck(false);controller.current?.edit({name,action:'remove_override',patch:{}});void controller.current?.preview();}}>Preview remove local override</button>
 ${state.previewed&&state.payload?.preview&&html`<div><p role="status">Preview only: ${state.payload.preview.name} — ${state.payload.preview.present?(state.payload.preview.enabled?'enabled':'disabled'):'removed'}. ${state.payload.preview.action==='remove_override'?'Removing the override may reveal an inherited server.':''}</p><pre aria-label="Effective server preview">${JSON.stringify(state.payload.preview.patch,null,2)}</pre></div>`}
 <label><input type="checkbox" checked=${ack} disabled=${busy||state.loading} onChange=${(e:Event)=>setAck((e.target as HTMLInputElement).checked)} /> I understand server Apply interrupts turns and reloads extensions.</label>
 <button class="settings-btn" type="button" disabled=${busy||state.loading||!ack||!state.previewed||!state.payload?.applyAvailable} onClick=${()=>void controller.current?.apply(ack)}>${state.applying?'Applying servers…':'Apply server change'}</button>${state.applied&&html`<p role="status">Server configuration saved and applied to current and new sessions.</p>`}</section>`;
}
