import { expect, test } from 'bun:test';
import { chromium } from 'playwright';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
const enabled = process.env.PICLAW_RUN_OPTIONAL_BROWSER_TESTS === '1';
const root = resolve(import.meta.dir, '../..');
const run = enabled ? test : test.skip;
run('Intel meters hide absent GPUs and expose accessible details on desktop/tablet', async () => {
 const tmp = await mkdtemp(join(tmpdir(),'intel-meter-browser-'));
 let browser;let server;
 try {
  const vendor=resolve(root,'web/src/vendor/preact-htm.js');
  const component=resolve(root,'web/src/components/system-meters-hud.ts');
  const entry=join(tmp,'entry.ts');
  await Bun.write(entry,`import {html,render} from ${JSON.stringify(vendor)};import {SystemMetersHud} from ${JSON.stringify(component)};localStorage.setItem('piclaw_system_meters_enabled','true');render(html\`<\${SystemMetersHud}/>\`,document.getElementById('root'));`);
  const build=await Bun.build({entrypoints:[entry],outdir:tmp,target:'browser',format:'esm'});expect(build.success).toBe(true);
  const gpu={id:'0000:00:02.0',name:'Intel Iris Xe',provider:'intel-drm-fdinfo',driver:'i915',status:'partial',sample_time_ms:Date.now(),busy_percent:63,engines:[{name:'render',capacity:1,busy_percent:63},{name:'video',capacity:2,busy_percent:0}],memory:{resident_bytes:677*1024**2,total_bytes:800*1024**2,shared_bytes:null},coverage:{clients:3,scanned_processes:90,unreadable_processes:1,unreadable_clients:0,truncated:false},history:[{timestamp_ms:Date.now()-2000,busy_percent:null,resident_bytes:null},{timestamp_ms:Date.now(),busy_percent:63,resident_bytes:677*1024**2}]};
  let devices:any[]=[];
  const base={cpu_percent:24,ram_percent:46,cpu_series:[20,24],ram_series:[40,46],swap_percent:null,swap_total_bytes:0};
  const css=await Bun.file(resolve(root,'web/static/classic/css/shell.css')).text();
  server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){const p=new URL(req.url).pathname;if(p==='/agent/system-metrics')return Response.json({...base,gpus:devices.map(d=>({...d,sample_time_ms:Date.now()}))});if(p==='/agent/ui-state')return Response.json({});if(p==='/entry.js')return new Response(Bun.file(join(tmp,'entry.js')),{headers:{'content-type':'text/javascript'}});return new Response(`<html><head><style>:root{--bg-primary:#111720;--text-primary:#edf3fc;--text-secondary:#a9b5c7;--border-color:#364254;--accent-color:#71a8ff;--success-color:#58c7a5}body{background:#111720;color:white;font:14px sans-serif;margin:0} ${css}</style></head><body><div id="root"></div><script type="module" src="/entry.js"></script></body></html>`,{headers:{'content-type':'text/html'}})}});
  browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-gpu']});
  const page=await browser.newPage({viewport:{width:1100,height:850},hasTouch:true});
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{localStorage.setItem('piclaw_system_meters_enabled','true');localStorage.setItem('piclaw_system_meters_collapsed','false');});
  await page.goto(server.url.toString());
  await page.locator('.system-meters-row.cpu').waitFor();
  expect(await page.locator('.intel-gpu').count()).toBe(0);
  expect(await page.locator('.system-meters-gpu-trigger, .system-meters-gpu-controls').count()).toBe(0);
  devices=[gpu];await page.reload();
  const activity=page.locator('.system-meters-row.intel-gpu');
  const memory=page.locator('.system-meters-row.intel-gmem');
  await activity.waitFor({timeout:8000});
  expect(await activity.innerText()).toContain('63%');
  expect(await activity.evaluate(el=>el.tagName)).toBe('BUTTON');
  expect(await page.locator('.system-meters-gpu-trigger, .system-meters-gpu-controls').count()).toBe(0);
  expect(await page.getByRole('dialog').count()).toBe(0);
  await activity.click();await page.getByRole('dialog').waitFor();
  expect(await page.getByRole('dialog').innerText()).toContain('Observed memory');expect(await page.getByRole('dialog').innerText()).toContain('677');
  expect(await page.getByRole('dialog').innerText()).not.toContain('Engines');
  expect(await page.locator('button button').count()).toBe(0);
  expect(await activity.getAttribute('aria-expanded')).toBe('true');
  expect(await page.locator('.system-meters-hud.is-collapsed').count()).toBe(0);
  await page.keyboard.press('Escape');expect(await page.getByRole('dialog').count()).toBe(0);
  expect(await activity.evaluate(el=>el===document.activeElement)).toBe(true);
  await memory.focus();await page.keyboard.press('Enter');await page.getByRole('dialog').waitFor();
  await page.getByRole('button',{name:'Close',exact:true}).click();
  expect(await memory.evaluate(el=>el===document.activeElement)).toBe(true);
  await memory.press('Space');await page.getByRole('dialog').waitFor();
  await page.mouse.click(10,700);expect(await page.getByRole('dialog').count()).toBe(0);
  await page.locator('.system-meters-row.cpu').click();
  await page.getByRole('button',{name:'Show system meters',exact:true}).waitFor();
  expect(await page.locator('.intel-gpu').count()).toBe(0);
  await page.getByRole('button',{name:'Show system meters',exact:true}).click();await activity.waitFor();
  await page.setViewportSize({width:390,height:850});
  const compactGpu=page.locator('.system-meters-compact-gpu.intel-gpu');
  const compactMem=page.locator('.system-meters-compact-gpu.intel-gmem');
  await compactGpu.waitFor();await compactGpu.tap();await page.getByRole('dialog').waitFor();
  const rect=await page.getByRole('dialog').boundingBox();expect(rect!.x).toBeGreaterThanOrEqual(0);expect(rect!.x+rect!.width).toBeLessThanOrEqual(391);
  await page.keyboard.press('Escape');
  expect(await compactGpu.evaluate(el=>el===document.activeElement)).toBe(true);
  await compactMem.press('Enter');await page.getByRole('dialog').waitFor();
  await compactMem.click();expect(await page.getByRole('dialog').count()).toBe(0);
  expect(await page.locator('.system-meters-gpu-trigger, .system-meters-gpu-controls').count()).toBe(0);
  devices=[{...gpu,busy_percent:null,status:'unavailable',memory:{resident_bytes:null},coverage:{clients:0},engines:[]}];await page.reload();
  await page.locator('.system-meters-compact-summary').waitFor();expect(await compactGpu.count()).toBe(0);expect(await compactMem.count()).toBe(0);
  devices=[gpu,{...gpu,id:'0000:03:00.0',name:'Second Intel GPU',busy_percent:22}];await page.reload();
  await page.getByRole('button',{name:/GPU1 .*Second Intel GPU details/}).click();
  await page.getByRole('dialog',{name:'Second Intel GPU details'}).waitFor();
  expect(await page.locator('button button').count()).toBe(0);
  // Live disappearance while open must clear the trigger, not reopen on return.
  devices=[];
  await page.getByRole('dialog').waitFor({state:'detached',timeout:8000});
  expect(await page.locator('.intel-gpu,.intel-gmem').count()).toBe(0);
  devices=[gpu,{...gpu,id:'0000:03:00.0',name:'Second Intel GPU',busy_percent:22}];
  await page.getByRole('button',{name:/GPU1 .*Second Intel GPU details/}).waitFor({timeout:8000});
  expect(await page.getByRole('dialog').count()).toBe(0);
  expect(await page.getByRole('button',{name:/GPU1 .*Second Intel GPU details/}).getAttribute('aria-expanded')).toBe('false');
  expect(errors).toEqual([]);
 } finally {await browser?.close();server?.stop(true);await rm(tmp,{recursive:true,force:true})}
},30000);
