import {beforeAll,expect,test} from 'bun:test';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {build} from 'esbuild';
import {chromium,webkit} from 'playwright';
import {withTempWorkspaceEnv} from '../helpers.js';
import {McpCodemodeController,resetMcpCodemodeRuntimeForTests} from '../../src/agent-pool/mcp-codemode-runtime.js';
import {hydrateMcpKeychainCredentials,resetMcpStartupStateForTests} from '../../src/secure/mcp-keychain.js';
import {handleMcpSettings} from '../../src/channels/web/handlers/mcp-settings.js';
const enabled=process.env.PICLAW_RUN_OPTIONAL_BROWSER_TESTS==='1'&&process.env.PICLAW_E2E_DISPOSABLE==='1',browserTest=enabled?test:test.skip;
const root=resolve(import.meta.dir,'../..'),bundles:Record<string,string>={};
beforeAll(async()=>{if(!enabled)return;for(const skin of ['classic','visual']){const source=skin==='classic'?`import{h,render}from'./web/src/vendor/preact-htm.js';import{McpServersSection}from'./web/src/components/settings/mcp-servers.ts';render(h(McpServersSection,{}),document.getElementById('root'));`:`import{h,render}from'preact';import{McpServersSection}from'./web/static/visual/frontend/src/panels/settings/McpServersSection.tsx';render(h(McpServersSection,{}),document.getElementById('root'));`;bundles[skin]=(await build({stdin:{contents:source,resolveDir:root,loader:'tsx'},bundle:true,format:'esm',platform:'browser',jsx:'automatic',jsxImportSource:'preact',write:false})).outputFiles[0].text;}},30000);
for(const [engineName,engine] of Object.entries({chromium,webkit}))for(const skin of ['classic','visual'])browserTest(`server Settings ${skin}/${engineName}: preview, Apply, private preservation, remove and owner denial`,async()=>{
 await withTempWorkspaceEnv('mcp-server-browser-',{},async ws=>{mkdirSync(join(ws.workspace,'.piclaw'),{recursive:true});mkdirSync(join(ws.workspace,'.pi'),{recursive:true});writeFileSync(join(ws.workspace,'.piclaw','config.json'),JSON.stringify({domains:{access:{mode:'single-user'}}}),{mode:0o600});const file=join(ws.workspace,'.pi','mcp.json');writeFileSync(file,JSON.stringify({mcpServers:{demo:{command:'never-run',args:['PRIVATE_SENTINEL']}}}),{mode:0o600});resetMcpStartupStateForTests();resetMcpCodemodeRuntimeForTests();await hydrateMcpKeychainCredentials(ws.workspace,()=>{throw Error('No secrets');});let authorized=true;const controller=new McpCodemodeController({blockMcpAdmissions(){},async fenceMcpAndSnapshot(){return[];},resumeMcpAdmissions(){},async quarantineMcpRuntime(){}});const owner={kind:'local',mode:'single-user',role:'admin',userId:'default',authentication:{method:'local',sessionId:null,expiresAt:null}};
 const server=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(req){const url=new URL(req.url);if(url.pathname==='/')return new Response(`<meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"><div id="root"></div><script type="module" src="/pane.js"></script>`,{headers:{'content-type':'text/html'}});if(url.pathname==='/pane.js')return new Response(bundles[skin],{headers:{'content-type':'text/javascript'}});if(url.pathname==='/style.css')return new Response(readFileSync(join(root,`web/static/${skin}/dist/app.bundle.css`)),{headers:{'content-type':'text/css'}});return handleMcpSettings({agentPool:{inspectMcpServers:(edit?:unknown)=>controller.inspectServers(edit),applyMcpServers:(input:any,check:()=>void,signal:AbortSignal)=>controller.applyServers(input,check,signal)},authGateway:{getPrincipal:()=>authorized?owner:null}} as any,req,url);}});
 const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:390,height:900}}),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.route('**/*',route=>new URL(route.request().url()).origin===server.url.origin?route.continue():route.abort());
 try{await page.goto(server.url.href);await page.getByRole('button',{name:'demo',exact:true}).waitFor();expect(await page.locator('body').innerText()).not.toContain('PRIVATE_SENTINEL');await page.getByRole('button',{name:'demo',exact:true}).click();const before=readFileSync(file,'utf8');await page.getByRole('button',{name:'Preview disable',exact:true}).click();await page.getByText('Preview only: demo — disabled.',{exact:true}).waitFor();expect(readFileSync(file,'utf8')).toBe(before);const apply=page.getByRole('button',{name:'Apply server change',exact:true});expect(await apply.isDisabled()).toBe(true);await page.getByLabel('I understand server Apply interrupts turns and reloads extensions.').check();await apply.click();await page.getByText('Server configuration saved and applied to current and new sessions.').waitFor();expect(JSON.parse(readFileSync(file,'utf8')).mcpServers.demo).toEqual({command:'never-run',args:['PRIVATE_SENTINEL'],disabled:true});await page.getByRole('button',{name:'demo',exact:true}).click();await page.getByRole('button',{name:'Preview remove local override'}).click();await page.getByText(/Preview only: demo — removed/).waitFor();await page.getByLabel('I understand server Apply interrupts turns and reloads extensions.').check();await apply.click();await page.getByText('Server configuration saved and applied to current and new sessions.').waitFor();expect(JSON.parse(readFileSync(file,'utf8')).mcpServers).toEqual({});authorized=false;await page.getByRole('button',{name:'Refresh servers',exact:true}).click();await page.getByRole('alert').waitFor();expect(await page.locator('body').innerText()).not.toContain('PRIVATE_SENTINEL');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);}finally{await browser.close();server.stop(true);resetMcpStartupStateForTests();resetMcpCodemodeRuntimeForTests();}
 });
},20000);
