import {beforeAll,expect,test} from 'bun:test';
import {resolve,join} from 'node:path';
import {build} from 'esbuild';
import {chromium,webkit} from 'playwright';
import {expectDividerChevrons} from './fixtures/divider-chevron-geometry.js';
const enabled=process.env.PICLAW_RUN_OPTIONAL_BROWSER_TESTS==='1'&&process.env.PICLAW_E2E_DISPOSABLE==='1',browserTest=enabled?test:test.skip,root=resolve(import.meta.dir,'../..');let bundle='';
beforeAll(async()=>{if(!enabled)return;bundle=(await build({stdin:{contents:`import{h,render}from'preact';import{ChatPanel}from'./web/static/visual/frontend/src/panels/ChatPanel.tsx';render(h(ChatPanel,{}),document.getElementById('root'));`,resolveDir:root,loader:'tsx'},bundle:true,format:'esm',platform:'browser',jsx:'automatic',jsxImportSource:'preact',write:false})).outputFiles[0].text;},30000);
for(const[name,engine]of Object.entries({chromium,webkit}))browserTest(`Visual ${name}: foreground catch-up fills new rows and divider preserves history until tapped`,async()=>{
 let count=80,malformed=false;const rows=()=>Array.from({length:count},(_,n)=>({id:1000+n,timestamp:'2026-10-05T00:00:00Z',data:{content:`Row ${n} ${'synthetic '.repeat(12)}`,is_bot_message:n%2===1,sender_name:'Fixture'}}));
 const server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){const url=new URL(req.url);if(url.pathname==='/')return new Response(`<link rel="stylesheet" href="/style.css"><style>html,body,#root{height:100%;margin:0}.chat{height:100%;display:flex;flex-direction:column}.chat__messages{flex:1;min-height:0}.message-list{height:100%}</style><div id="root"></div><script type="module" src="/pane.js"></script>`,{headers:{'content-type':'text/html'}});if(url.pathname==='/pane.js')return new Response(bundle,{headers:{'content-type':'text/javascript'}});if(url.pathname==='/style.css')return new Response(Bun.file(join(root,'web/static/visual/dist/app.bundle.css')),{headers:{'content-type':'text/css'}});if(url.pathname==='/malformed'){malformed=true;return Response.json({ok:true});}if(url.pathname==='/timeline'){if(malformed)return Response.json({ok:true});const before=Number(url.searchParams.get('before'))||Infinity,limit=Number(url.searchParams.get('limit'))||50,all=rows().filter(row=>row.id<before),posts=all.slice(-limit);return Response.json({posts,has_more:all.length>posts.length});}if(url.pathname==='/arrive'){count=165;return Response.json({ok:true});}if(url.pathname==='/agent/status')return Response.json({status:{state:'idle'},model:{},context:{},metrics:{}});if(url.pathname==='/agent/default/queue')return Response.json({items:[],count:0});return Response.json({ok:true,commands:[],tasks:[],chats:[],current_model:'synthetic',enabled:false});}});
 const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:820,height:1180}}),errors:string[]=[];page.setDefaultTimeout(5000);page.on('pageerror',error=>errors.push(error.message));await page.addInitScript(()=>{const sources:EventTarget[]=[];class SSE extends EventTarget{readyState=1;onopen:any;constructor(){super();sources.push(this);setTimeout(()=>this.onopen?.(new Event('open')),0);}close(){}}Object.defineProperty(window,'EventSource',{value:SSE});(window as any).fixtureSse=(kind:string,body:unknown)=>sources.forEach(source=>source.dispatchEvent(new MessageEvent(kind,{data:JSON.stringify(body)})));});await page.route('**/*',route=>new URL(route.request().url()).origin===server.url.origin?route.continue():route.abort());
 try{await page.goto(server.url.href);await page.locator('[data-message-id="1079"]').waitFor();await page.waitForTimeout(200);await page.locator('.message-list').evaluate((el:HTMLElement)=>{el.scrollTop=-1000;});await page.waitForTimeout(100);expect(await page.locator('.message-list').evaluate((el:HTMLElement)=>el.scrollTop)).toBeLessThan(-100);await page.evaluate(async()=>{await fetch('/arrive');(window as any).fixtureSse('new_post',{id:1164,data:{content:'Isolated newest SSE',timestamp:'2026-10-05T00:00:00Z'}});window.dispatchEvent(new Event('pageshow'));});await page.getByRole('button',{name:'New messages — jump to latest'}).waitFor();await expectDividerChevrons(page,'.compose-latest-divider');expect(await page.locator('[data-message-id="1120"]').count()).toBe(1);expect(await page.locator('.message-list').evaluate((el:HTMLElement)=>el.scrollTop)).toBeLessThan(-100);await page.getByRole('button',{name:'New messages — jump to latest'}).click();await page.waitForTimeout(150);expect(Math.abs(await page.locator('.message-list').evaluate((el:HTMLElement)=>el.scrollTop))).toBeLessThan(2);expect(await page.locator('[data-message-id="1164"]').count()).toBe(1);expect(await page.locator('[data-message-id]').first().getAttribute('data-message-id')).toBe('1164');await page.evaluate(()=>window.dispatchEvent(new CustomEvent('piclaw:scroll-to-message',{detail:{id:1005}})));await page.waitForFunction(()=>document.querySelectorAll('[data-message-id]').length<=50);await page.locator('[data-message-id="1005"]').waitFor();await page.evaluate(()=>window.dispatchEvent(new Event('pageshow')));await page.locator('[data-message-id="1090"]').waitFor();expect(await page.locator('[data-message-id="1090"]').count()).toBe(1);const retained=await page.locator('[data-message-id]').count();await page.evaluate(async()=>{await fetch('/malformed');window.dispatchEvent(new Event('pageshow'));});await page.getByText('Could not refresh messages. Try again.',{exact:false}).waitFor();expect(await page.locator('[data-message-id]').count()).toBe(retained);expect(errors).toEqual([]);}
 catch(error){console.log(JSON.stringify(await page.evaluate(()=>({text:document.body.innerText.slice(-1200),scroll:document.querySelector('.message-list')?.scrollTop,count:document.querySelectorAll('[data-message-id]').length}))));throw error;}finally{await browser.close();server.stop(true);}
},20000);
