import {beforeAll,afterAll,expect,test} from 'bun:test';
import {join} from 'node:path';
import {chromium,webkit} from 'playwright';
import {expectDividerChevrons} from './fixtures/divider-chevron-geometry.js';
const enabled=process.env.PICLAW_RUN_OPTIONAL_BROWSER_TESTS==='1',browserTest=enabled?test:test.skip;
let server:ReturnType<typeof Bun.serve>;
let latestCount=160;
const posts=(count=160)=>Array.from({length:count},(_,n)=>({id:1000+n,type:n%2?'agent':'user',data:{content:`Synthetic row ${n}\n\n${'Row. '.repeat(6)}`,timestamp:'2026-10-05T00:00:00Z',is_bot_message:n%2===1}}));
beforeAll(async()=>{if(!enabled)return;const result=await Bun.build({entrypoints:[join(import.meta.dir,'fixtures/chat-return-scroll-fixture.ts')],target:'browser',format:'esm'});if(!result.success)throw Error(result.logs.join('\n'));const bundle=await result.outputs[0].text();server=Bun.serve({hostname:'127.0.0.1',port:0,fetch(req){const url=new URL(req.url);if(url.pathname==='/fixture.js')return new Response(bundle,{headers:{'content-type':'text/javascript'}});if(url.pathname==='/timeline'){const before=Number(url.searchParams.get('before'))||Infinity,limit=Number(url.searchParams.get('limit'))||10;const rows=posts(latestCount).filter(row=>row.id<before).reverse().slice(0,limit);return Response.json({posts:rows,has_more:rows.length>0&&rows.at(-1)!.id>1000});}if(url.pathname==='/arrivals'){latestCount=Number(url.searchParams.get('count'))||160;return Response.json({ok:true});}if(url.pathname.startsWith('/static/'))return new Response(Bun.file(join(import.meta.dir,'../../web',url.pathname)));return new Response(`<link rel="stylesheet" href="/static/classic/dist/app.bundle.css"><style>html,body,#app{height:100%;margin:0}.timeline{min-height:0;flex:1}.compose-box{flex:none}.timeline-content>.post{min-height:74px}</style><main id="app"></main><script type="module" src="/fixture.js"></script>`,{headers:{'content-type':'text/html'}});}});},30000);
afterAll(()=>server?.stop(true));
for(const[name,engine]of Object.entries({chromium,webkit}))browserTest(`${name}: returning a tall viewport with short rows covers it without a scroll event`,async()=>{
 const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:1024,height:600}});await page.route('**/*',route=>new URL(route.request().url()).origin===server.url.origin?route.continue():route.abort());
 try{await page.goto(`${server.url}?count=160`);await page.waitForFunction(()=>document.body.dataset.ready==='a');await page.evaluate(value=>(window as any).timelineFixture.replace(value),posts());await page.waitForTimeout(250);await page.setViewportSize({width:1024,height:2000});await page.evaluate(()=>{window.dispatchEvent(new Event('pageshow'));});await page.waitForTimeout(250);
 const geometry=await page.locator('#fixture-timeline').evaluate(root=>{const box=root.getBoundingClientRect(),rows=[...root.querySelectorAll('.post')].map(row=>row.getBoundingClientRect()).filter(row=>row.bottom>box.top&&row.top<box.bottom);return{height:box.height,count:rows.length,gap:rows.length?Math.max(0,Math.min(...rows.map(row=>row.top))-box.top):box.height,scrollTop:(root as HTMLElement).scrollTop};});
 expect(geometry.height).toBeGreaterThan(1200);expect(geometry.count).toBeGreaterThan(16);expect(geometry.gap).toBeLessThan(80);expect(Math.abs(geometry.scrollTop)).toBeLessThan(2);
 }finally{await browser.close();}
},15000);
for(const[name,engine]of Object.entries({chromium,webkit}))browserTest(`${name}: dozens of arrivals fill cache gap and divider jumps without stealing history scroll`,async()=>{
 latestCount=160;const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:1024,height:768}});await page.route('**/*',route=>new URL(route.request().url()).origin===server.url.origin?route.continue():route.abort());
 try{await page.goto(`${server.url}?count=160`);await page.waitForFunction(()=>document.body.dataset.ready==='a');await page.waitForTimeout(200);await page.locator('#fixture-timeline').evaluate((root:HTMLElement)=>{root.scrollTop=-1200;});await page.waitForTimeout(150);await page.getByRole('button',{name:'Jump to latest message',exact:true}).waitFor();expect(await page.locator('#fixture-timeline').evaluate((root:HTMLElement)=>root.scrollTop)).toBeLessThan(-100);
 await page.evaluate(async()=>{await fetch('/arrivals?count=245');await(window as any).timelineFixture.refresh();});await page.waitForTimeout(250);expect(await page.locator('#fixture-timeline').evaluate((root:HTMLElement)=>root.scrollTop)).toBeLessThan(-100);await page.getByRole('button',{name:'New messages — jump to latest'}).waitFor();await page.getByRole('button',{name:'New messages — jump to latest'}).click();await page.waitForTimeout(200);expect(Math.abs(await page.locator('#fixture-timeline').evaluate((root:HTMLElement)=>root.scrollTop))).toBeLessThan(2);await page.locator('#post-1244').waitFor();expect(await page.getByRole('button',{name:'New messages — jump to latest'}).count()).toBe(0);
 // All pages between the old cache suffix and the latest row were loaded;
 // a history reveal finds the previously omitted middle without another GET.
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('piclaw:reveal-timeline-post',{detail:{id:1195}})));await page.locator('#post-1195').waitFor();
 }finally{await browser.close();}
},15000);
for(const[name,engine]of Object.entries({chromium,webkit}))browserTest(`${name}: cached switch-away return after 85 arrivals reaches the latest and retains the middle`,async()=>{
 latestCount=160;const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:820,height:1180}});await page.route('**/*',route=>new URL(route.request().url()).origin===server.url.origin?route.continue():route.abort());
 try{await page.goto(`${server.url}?count=160`);await page.waitForFunction(()=>document.body.dataset.ready==='a');await page.waitForTimeout(200);await page.locator('#fixture-timeline').evaluate((root:HTMLElement)=>{root.scrollTop=-900;});await page.locator('#switch-b').click();await page.waitForFunction(()=>document.body.dataset.ready==='b');await page.evaluate(()=>fetch('/arrivals?count=245'));await page.locator('#switch-a').click();await page.waitForFunction(()=>document.body.dataset.ready==='a');await page.locator('#post-1244').waitFor();expect(Math.abs(await page.locator('#fixture-timeline').evaluate((root:HTMLElement)=>root.scrollTop))).toBeLessThan(2);await page.evaluate(()=>window.dispatchEvent(new CustomEvent('piclaw:reveal-timeline-post',{detail:{id:1195}})));await page.locator('#post-1195').waitFor();expect(await page.locator('#post-1195').count()).toBe(1);
 }finally{await browser.close();}
},15000);
for(const[name,engine]of Object.entries({chromium,webkit}))browserTest(`${name}: dragging the divider resizes without jumping; tapping it jumps`,async()=>{
 latestCount=160;const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:1024,height:900}});await page.route('**/*',route=>new URL(route.request().url()).origin===server.url.origin?route.continue():route.abort());
 try{await page.goto(`${server.url}?count=160`);await page.waitForFunction(()=>document.body.dataset.ready==='a');await page.waitForTimeout(200);await page.locator('#fixture-timeline').evaluate((root:HTMLElement)=>{root.scrollTop=-900;});await page.waitForTimeout(150);await expectDividerChevrons(page,'.compose-resize-handle');const handle=page.locator('.compose-resize-handle'),box=await handle.boundingBox();expect(box).not.toBeNull();await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2);await page.mouse.down();await page.mouse.move(box!.x+box!.width/2,box!.y-60,{steps:4});await page.mouse.up();expect(await page.locator('#fixture-timeline').evaluate((root:HTMLElement)=>root.scrollTop)).toBeLessThan(-100);await page.getByRole('button',{name:'Jump to latest message',exact:true}).click();await page.waitForTimeout(150);expect(Math.abs(await page.locator('#fixture-timeline').evaluate((root:HTMLElement)=>root.scrollTop))).toBeLessThan(2);
 }finally{await browser.close();}
},15000);
browserTest('failed older-page admission retries the same cursor rather than permanently suppressing it',async()=>{
 latestCount=160;const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:820,height:1180}});let failures=0,attempts=0;
 await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin!==server.url.origin)return route.abort();if(url.pathname==='/timeline'&&url.searchParams.has('before')){attempts++;if(failures++===0)return route.fulfill({status:503,json:{error:'synthetic failure'}});}return route.continue();});
 try{await page.goto(`${server.url}?count=160`);await page.waitForFunction(()=>document.body.dataset.ready==='a');await page.waitForTimeout(250);const failed=await page.evaluate(async()=>{const rejected=await(window as any).timelineFixture.loadMore({preserveScroll:false}).then(()=>false,()=>true);await(window as any).timelineFixture.loadMore({preserveScroll:false});return rejected;});expect(failed).toBe(true);expect(attempts).toBeGreaterThanOrEqual(2);
 }finally{await browser.close();}
},15000);
for(const[name,engine]of Object.entries({chromium,webkit}))browserTest(`${name}: reverse scroll anchor remains on the same content after appended rows`,async()=>{
 latestCount=160;const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:820,height:1180}});await page.route('**/*',route=>new URL(route.request().url()).origin===server.url.origin?route.continue():route.abort());
 try{await page.goto(`${server.url}?count=30`);await page.waitForFunction(()=>document.body.dataset.ready==='a');await page.waitForTimeout(200);const result=await page.locator('#fixture-timeline').evaluate(async(root:HTMLElement)=>{root.scrollTop=-700;await new Promise(resolve=>requestAnimationFrame(resolve));const before=root.scrollHeight+root.scrollTop;(window as any).timelineFixture.preserve(()=>{const row=document.createElement('div');row.style.height='320px';row.style.flex='0 0 320px';root.querySelector('.timeline-content')!.appendChild(row);});await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return{before,after:root.scrollHeight+root.scrollTop,top:root.scrollTop};});expect(Math.abs(result.after-result.before)).toBeLessThan(2);expect(result.top).toBeLessThan(-700);
 }finally{await browser.close();}
},15000);
for(const[name,engine]of Object.entries({chromium,webkit}))browserTest(`${name}: an SSE arrival before catch-up cannot hide middle pages or auto-follow a reader 100px away`,async()=>{
 latestCount=160;const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:820,height:1180}});await page.route('**/*',route=>new URL(route.request().url()).origin===server.url.origin?route.continue():route.abort());
 try{await page.goto(`${server.url}?count=160`);await page.waitForFunction(()=>document.body.dataset.ready==='a');await page.waitForTimeout(200);await page.locator('#fixture-timeline').evaluate((root:HTMLElement)=>{root.scrollTop=-100;});await page.waitForTimeout(100);await page.evaluate(async()=>{await fetch('/arrivals?count=245');(window as any).timelineFixture.arrive({id:1244,data:{content:'Newest isolated SSE row',timestamp:'2026-10-05T00:00:00Z'}});await(window as any).timelineFixture.refresh();});await page.waitForTimeout(150);expect(await page.locator('#fixture-timeline').evaluate((root:HTMLElement)=>root.scrollTop)).toBeLessThan(-60);await page.getByRole('button',{name:'New messages — jump to latest'}).waitFor();await page.evaluate(()=>window.dispatchEvent(new CustomEvent('piclaw:reveal-timeline-post',{detail:{id:1195}})));await page.locator('#post-1195').waitFor();expect(await page.locator('#post-1195').count()).toBe(1);
 }finally{await browser.close();}
},15000);
for(const[name,engine]of Object.entries({chromium,webkit}))browserTest(`${name}: older context replacement invalidates previous continuity metadata`,async()=>{
 latestCount=245;const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:820,height:1180}});await page.route('**/*',route=>new URL(route.request().url()).origin===server.url.origin?route.continue():route.abort());
 try{await page.goto(`${server.url}?count=160`);await page.waitForFunction(()=>document.body.dataset.ready==='a');await page.locator('#post-1244').waitFor();await page.evaluate(()=>(window as any).timelineFixture.replace(Array.from({length:20},(_,n)=>({id:1000+n,data:{content:'Historical replacement'}}))));await page.waitForTimeout(100);await page.evaluate(()=>(window as any).timelineFixture.refresh());await page.locator('#post-1244').waitFor();await page.evaluate(()=>window.dispatchEvent(new CustomEvent('piclaw:reveal-timeline-post',{detail:{id:1195}})));await page.locator('#post-1195').waitFor();expect(await page.locator('#post-1195').count()).toBe(1);
 }finally{await browser.close();}
},15000);
