import assert from 'node:assert/strict';
const dir=import.meta.dir;
const input=await Bun.file(`${dir}/inputs.json`).json();const s=input.cacheShares;
const ids={fable:'anthropic/claude-fable-5.1',astra:'openai-codex/gpt-6-astra',old:'anthropic/claude-fable-5',sol:'openrouter/openai/gpt-5.6-sol',solNative:'openai/gpt-5.6-sol',terra:'openai/gpt-5.6-terra',deep:'openrouter/deepseek/deepseek-v4-pro-0813',kimi:'openrouter/moonshotai/kimi-k3',mini:'openrouter/minimax/minimax-m3',flash:'openrouter/deepseek/deepseek-v4-flash-0731'};
const labels={fable:'Fable 5.1',astra:'Astra',old:'Fable 5',sol:'Sol · OpenRouter',solNative:'Sol · native/Copilot',terra:'Terra · native',deep:'DeepSeek V4 Pro 0813',kimi:'Kimi K3',mini:'MiniMax M3',flash:'DeepSeek V4 Flash 0731'};
const rows=[
 {id:'hard',name:'Difficult debugging / multi-file refactor',minutes:25,tasks:1,calls:6,promptPerCall:50000,outputPerTask:15000,frontier:['fable','astra'],precursor:['sol','terra'],open:['deep','kimi'],default:'fable',why:'Start with Fable for sustained code changes; escalate to Astra for an independent reasoning pass. DeepSeek is a lower-cost trial when tests can judge success.'},
 {id:'code',name:'Routine implementation, tests and review',minutes:20,tasks:3,calls:4,promptPerCall:25000,outputPerTask:8000,frontier:['fable','astra'],precursor:['sol','terra'],open:['mini','deep'],default:'sol',why:'Sol is the practical default; use Terra or MiniMax for bounded changes with strong tests. Frontier pricing is usually unnecessary for this row.'},
 {id:'ops',name:'Infrastructure diagnosis / scripting',minutes:15,tasks:1,calls:3,promptPerCall:20000,outputPerTask:4000,frontier:['astra','fable'],precursor:['sol','terra'],open:['deep','mini'],default:'sol',why:'Prefer a proven tool workflow over a speculative capability win. Astra is an escalation option for ambiguous diagnosis; keep state-changing commands gated.'},
 {id:'docs',name:'Research and long-document synthesis',minutes:30,tasks:1,calls:4,promptPerCall:40000,outputPerTask:8000,frontier:['fable','astra'],precursor:['sol','old'],open:['kimi','deep'],default:'kimi',why:'Kimi is the open-weight trial for document-heavy work; Fable is the premium option. Require source checks on every route. Fable 5 is a compatibility fallback, not a good new purchase.'},
 {id:'small',name:'Extraction, short summaries and transformations',minutes:10,tasks:2,calls:2,promptPerCall:10000,outputPerTask:2000,frontier:['fable','astra'],precursor:['terra','sol'],open:['flash','mini'],default:'flash',why:'Use Flash first for well-specified, verifiable output. Escalate only on validation failures; a frontier model is poor value here.'}
];
const rate=(key:string)=>input.models[ids[key]];
const cost=(key:string,row:any,outputScale=1)=>{const r=rate(key);const prompt=row.calls*row.promptPerCall;return (prompt*(s.input*r.input+s.read*(r.cr??r.input)+s.write*(r.cw??r.input))+row.outputPerTask*outputScale*r.output)/1e6;};
const days=30;const month=(choose:(r:any)=>string,scale=1)=>rows.reduce((n,r)=>n+days*r.tasks*cost(choose(r),r,scale),0);
const profiles={recommended:month(r=>r.default),frontierByWorkload:month(r=>r.frontier[0]),precursorByWorkload:month(r=>r.precursor[0]),openByWorkload:month(r=>r.open[0]),allFable:month(()=> 'fable'),allAstra:month(()=> 'astra'),allSolRouter:month(()=> 'sol'),allSolNative:month(()=> 'solNative')};
const outputSensitivity=[.5,1,2].map(multiplier=>({multiplier,usd:month(r=>r.default,multiplier)}));
const dollars=(n:number)=>`$${n.toFixed(2)}`;const taskMoney=(n:number)=>`$${n.toFixed(n<.01?4:3)}`;const price=(n:number|null)=>n==null?'—':`$${Number(n.toFixed(6))}`;const e=(x:any)=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const table=(heads:string[],data:string[][])=>`<div class="scroll"><table><thead><tr>${heads.map(x=>`<th>${e(x)}</th>`).join('')}</tr></thead><tbody>${data.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const rank=(keys:string[],r:any)=>keys.map((k,i)=>`<div>${i+1}. <b>${e(labels[k])}</b><br><small>${taskMoney(cost(k,r))} / task</small></div>`).join('');
const modelRows=Object.keys(ids).map(key=>{const r=rate(key);return [e(labels[key]),e(r.provider),price(r.input),price(r.output),price(r.cr),price(r.cw)];});
const scenarioRows=rows.map(r=>[e(r.name),`${r.tasks}`,`${r.minutes}`,`${r.calls} × ${(r.promptPerCall/1000)}K`,`${r.outputPerTask/1000}K`,e(labels[r.default]),dollars(days*r.tasks*cost(r.default,r))]);
const strategyRows=[['Frontier choices, by workload',profiles.frontierByWorkload],['Precursor choices, by workload',profiles.precursorByWorkload],['Open-weight choices, by workload',profiles.openByWorkload],['Recommended mixed routing',profiles.recommended],['All Fable 5.1',profiles.allFable],['All Astra',profiles.allAstra],['All Sol via OpenRouter',profiles.allSolRouter],['All Sol via native API / Copilot equivalent',profiles.allSolNative]].map(([n,v])=>[e(n),dollars(v as number),`${dollars((v as number)*.8)}–${dollars((v as number)*1.2)}`]);
const sections=[
 ['Scope and ranking meaning',`<p>This is a <b>task-based purchasing/routing comparison</b>, not a replay of production usage. Frontier = newest premium closed models (Fable 5.1, Astra). Precursor = earlier closed families (Sol/Terra, Fable 5). Open = models with published weights, accessed here through OpenRouter; this label does not imply low capability or unrestricted licences.</p><p><b>The order is my provisional trial recommendation for each workload, not a measured quality leaderboard.</b> Public model-purpose descriptions, prices, our established Sol preference and the ability to validate outputs inform it. We have not run a matched benchmark of these models. Costs assume equal work and no retries; a better model can earn its premium by avoiding failures.</p>`],
 ['1 · Workload rankings within each model class',table(['Workload','Frontier · trial order','Precursor · trial order','Open-weight · trial order','Start here / rationale'],rows.map(r=>[e(r.name),rank(r.frontier,r),rank(r.precursor,r),rank(r.open,r),`<b>${e(labels[r.default])}</b><p>${e(r.why)}</p>`]))],
 ['2 · Recommended model prices',`<p>USD per million tokens. Standard, short-context pricing; explicit route identity. Fable rates are native Anthropic and matched the retrieved OpenRouter quote. Astra uses the native OpenAI tariff (the Codex subscription is not billed as a general API key).</p>${table(['Model / route','Provider','Input','Output','Cache read','Cache write'],modelRows)}<p>— means unpublished: cost estimates charge ordinary input for that cache category, not zero. OpenRouter quotes are route prices, not guaranteed prices at every upstream endpoint; funding fees and tax are excluded. Sol native pricing is promotional at least through 21 November 2026. OpenAI pricing above 272K prompt tokens per request changes; none of the illustrative requests below crosses that threshold.</p><p><b>Fable 5 is not a value recommendation:</b> Fable 5.1 has the same input/output tariff and cheaper cached reads. Keep the predecessor only for model-access constraints or verified regressions. OpenRouter Sol is half the native/Copilot input/output tariff; do not interchange those prices.</p>`],
 ['3 · A moderate 2.5-hour day: explicit task assumptions',`<p>8 human tasks/day, 150 minutes/day, 30 days/month. These counts are a scenario, not a claim about your habits. Each task can involve multiple model calls. Outputs include billed reasoning once. Human time includes reading, editing and checking, not continuous model generation.</p>${table(['Task','Tasks/day','Minutes/task','Calls/task × prompt/call','Output/task, all calls','Selected model','Monthly API estimate'],scenarioRows)}<p>Only the <b>prompt-category mix</b> is borrowed from our ledger: ${(s.read*100).toFixed(2)}% cache reads, ${(s.write*100).toFixed(2)}% cache writes, ${(s.input*100).toFixed(2)}% uncached input. No historical request count or absolute token volume is reused. Cache hits as a share of prompt tokens are distinct from the earlier 94.35% share of all tokens.</p><p>The assumed mix produces 25.8M prompt tokens and 1.65M billed output tokens/month over 870 model calls. Cache reuse must actually carry over to these routes for the costs to hold. Model tokenisation, retries, output length and cache lifetime may differ. Five-minute Fable cache writes are assumed.</p>`],
 ['4 · Monthly scenario comparison',`${table(['Routing strategy','2.5h/day · 30 days','2–3h/day · same mix scaled'],strategyRows)}<p>The range merely scales task volume 0.8–1.2×; it is <b>not</b> a confidence interval. At 22 active days/month multiply by 22/30. The mixed strategy costs ${dollars(outputSensitivity[0].usd)} / ${dollars(outputSensitivity[1].usd)} / ${dollars(outputSensitivity[2].usd)} with half / baseline / double the assumed output volume, holding prompts fixed.</p><p>Under this scenario Fable 5.1 is ${((1-profiles.allFable/profiles.allAstra)*100).toFixed(1)}% cheaper than Astra—not the 69.9% from the long-context production replay. Task assumptions, output share and request size change the purchasing decision.</p>`],
 ['5 · How this fits current plans',`<ul><li><b>API / OpenRouter:</b> use the dollar estimates above as a top-up budget, not a flat-rate allowance. Start with capped spending and measure cost per successful task; no Azure or Cerebras price is silently substituted.</li><li><b>ChatGPT / Codex:</b> Plus $20/month; Pro 5× $100; Pro 20× $200. A Plus trial is a lower-commitment way to test subscription capacity, but neither 2–3h/day nor API-equivalent dollars proves it will fit. Rolling and weekly usage limits depend on model and workload. Subscription access is through eligible products/integrations, not generic API credits.</li><li><b>Claude:</b> Pro $20/month (or $200/year); Max from $100/month, with 5× and 20× usage tiers. Use eligible Claude/Claude Code access; do not count this as Anthropic API credit in Piclaw. Model entitlements and rolling limits need checking before selecting Fable as the default.</li><li><b>Copilot:</b> Pro $10/month, Pro+ $39, Max $100. Currently displayed credit totals are $15 / $70 / $200, comprising base $10 / $39 / $100 plus variable flex allotments. The native Sol scenario is ${dollars(profiles.allSolNative)}: above Pro and Pro+ base allowances, but within Pro+'s currently displayed total. Do not use the cheaper OpenRouter Sol quote to predict Copilot consumption. Premium-model access and other credit-consuming features can change the fit.</li></ul><p><b>Practical recommendation:</b> benchmark the mixed routing above against an all-Sol baseline. Pay for a premium subscription only if its eligible model access, successful-task rate and observed limits beat that API budget. The available evidence does not establish a guaranteed number of problems solved per plan.</p>`],
 ['Evidence and boundaries',`<ul><li><a href="https://developers.openai.com/api/docs/pricing.md">OpenAI pricing</a>; <a href="https://developers.openai.com/api/docs/models/gpt-6-astra.md">Astra model guide</a>; <a href="https://developers.openai.com/api/docs/models/gpt-5.6-sol.md">Sol model guide</a>.</li><li><a href="https://platform.claude.com/docs/en/about-claude/pricing.md">Anthropic pricing</a>; <a href="https://openrouter.ai/api/v1/models">OpenRouter prices and model descriptions</a>.</li><li><a href="https://developers.openai.com/codex/pricing">Codex plans</a>; <a href="https://claude.com/pricing">Claude plans</a>; <a href="https://github.com/features/copilot/plans">Copilot plans and variable flex allotments</a>.</li></ul><p>Pricing snapshot: 5 September 2026. Prices are sourced; workload sizes are assumptions; ranking order is editorial. Azure tariffs and Cerebras GLM pricing remain unverified and therefore are not competitive numeric quotations in this matrix. Existing production data, defaults and subscriptions are untouched.</p>`]
];
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Models ranked by workload</title><style>:root{--bg:#f6f7f9;--panel:white;--fg:#253140;--muted:#586575;--line:#d8e0e8;--accent:#0f766e}@media(prefers-color-scheme:dark){:root{--bg:#10151e;--panel:#18212d;--fg:#e5edf5;--muted:#afbbc9;--line:#344151;--accent:#5eead4}}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.55 system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}main{max-width:1440px;margin:auto;padding:24px 18px}h1{font-size:30px;line-height:1.2}h2{font-size:21px;margin-top:0}header p,small{color:var(--muted)}section{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:20px;margin:18px 0}p{max-width:1150px}a{color:var(--accent)}li{margin:8px 0}.scroll{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid var(--line);padding:10px;min-width:100px}th{color:var(--muted)}td div+div{margin-top:10px}td p{margin:8px 0}small{font-variant-numeric:tabular-nums}section:first-of-type{border-left:3px solid var(--accent)}@media(max-width:600px){main{padding:14px 8px}section{padding:14px}h1{font-size:25px}table{min-width:760px}}@media print{main{max-width:none;padding:0}section{break-inside:avoid}.scroll{overflow:visible}body{font-size:12px}}</style></head><body><main><header><h1>Models ranked by workload</h1><p>Frontier · precursor · open weights<br>2–3 hours/day · task-based estimates · our caching ratio · 5 September 2026</p></header>${sections.map(([h,b])=>`<section><h2>${e(h)}</h2>${b}</section>`).join('')}</main></body></html>`;
const result={assumptions:{days,rows,cacheShares:s,rankings:'Editorial trial order, not benchmark results'},profiles,outputSensitivity,costsPerTask:rows.map(r=>({workload:r.name,usd:Object.fromEntries(Object.keys(ids).map(k=>[k,cost(k,r)]))}))};
assert(Math.abs(s.input+s.read+s.write-1)<1e-12);
assert.equal(rows.reduce((n,r)=>n+r.tasks*r.minutes,0),150);assert.equal(rows.reduce((n,r)=>n+r.tasks,0),8);
assert.equal(rows.reduce((n,r)=>n+r.tasks*r.calls,0)*days,870);
assert.equal(rows.reduce((n,r)=>n+r.tasks*r.calls*r.promptPerCall,0)*days,25_800_000);
assert.equal(rows.reduce((n,r)=>n+r.tasks*r.outputPerTask,0)*days,1_650_000);
assert(Math.abs(profiles.allSolNative-2*profiles.allSolRouter)<1e-8);
assert(Math.abs(profiles.allAstra-profiles.allFable-25_800_000*s.read*.75/1e6)<1e-8);
assert(rows.every(r=>r.promptPerCall<272000));assert(Object.values(profiles).every(x=>Number.isFinite(x)&&x>0));
await Bun.write(`${dir}/report.html`,html);await Bun.write(`${dir}/scenario.json`,JSON.stringify(result,null,2));
console.log(JSON.stringify({status:'PASS',profiles,outputSensitivity,costsPerTask:result.costsPerTask},null,2));
