import { createHash } from 'node:crypto';
import { constants, lstatSync, openSync, closeSync, fstatSync, readSync, opendirSync, realpathSync } from 'node:fs';
import { basename, dirname, extname, relative, resolve, sep } from 'node:path';
import { parseFrontmatter } from '@earendil-works/pi-coding-agent';
import { getWorkspaceDir } from './config-context.js';
import { readAccessConfig } from './config-access.js';
import { ChatAccessDenied } from '../db/session-ownership.js';

const MAX_ENTRIES=2000,MAX_SKILLS=500,MAX_DEPTH=5,MAX_FILE=64*1024;
export interface FamilySkillProvenance {name:string;description:string;provenance:'packaged'|'shared-workspace';source:string;sha256:string;selected:boolean;collision_with:string[]}
interface ScanBudget {entries:number;skills:number}
const hash=(value:Uint8Array)=>createHash('sha256').update(value).digest('hex');
function frontmatter(text:string,path:string,root:string){let value:ReturnType<typeof parseFrontmatter>;try{value=parseFrontmatter(text);}catch{return null;}const declared=value.frontmatter.name,description=value.frontmatter.description;if(typeof description!=='string'||!description.trim()||description.length>1024)return null;const source=relative(root,path),fallback=basename(path)==='SKILL.md'?basename(dirname(path)):basename(path,extname(path)),name=typeof declared==='string'&&declared.trim()?declared.trim():fallback;if(!name||name.length>64)return null;return {name,description};}
const compare=(a:string,b:string)=>{const left=[...a],right=[...b],length=Math.min(left.length,right.length);for(let i=0;i<length;i++){const l=left[i]!.codePointAt(0)!,r=right[i]!.codePointAt(0)!;if(l!==r)return l-r;}return left.length-right.length;};
function canonical(path:string,boundary:string){const target=resolve(path),limit=resolve(boundary);if(target!==limit&&!target.startsWith(limit+sep))throw new ChatAccessDenied();let current=target;for(;;){const stat=lstatSync(current);if(stat.isSymbolicLink()||!stat.isDirectory())throw new ChatAccessDenied();if(current===limit)break;current=dirname(current);}if(realpathSync(target)!==target)throw new ChatAccessDenied();}
function read(path:string,root:string){const absolute=resolve(path),stat=lstatSync(absolute);if(stat.isSymbolicLink()||!stat.isFile()||stat.nlink!==1||stat.size>MAX_FILE||!absolute.startsWith(resolve(root)+sep))throw new ChatAccessDenied();const fd=openSync(absolute,constants.O_RDONLY|constants.O_NOFOLLOW);try{const opened=fstatSync(fd);if(!opened.isFile()||opened.nlink!==1||opened.dev!==stat.dev||opened.ino!==stat.ino||opened.size!==stat.size||opened.size>MAX_FILE)throw new ChatAccessDenied();const bytes=Buffer.alloc(opened.size);let offset=0;while(offset<bytes.length){const n=readSync(fd,bytes,offset,bytes.length-offset,offset);if(!n)throw new ChatAccessDenied();offset+=n;}const after=fstatSync(fd);if(after.dev!==opened.dev||after.ino!==opened.ino||after.size!==opened.size||after.mtimeMs!==opened.mtimeMs||realpathSync(absolute)!==absolute)throw new ChatAccessDenied();let text:string;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{throw new ChatAccessDenied();}return {bytes,text};}finally{closeSync(fd);}}
function scan(root:string,provenance:FamilySkillProvenance['provenance'],validate:()=>void,budget:ScanBudget,optional=false){const output:Array<Omit<FamilySkillProvenance,'selected'|'collision_with'>>=[];if(optional){try{lstatSync(root);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return output;throw new ChatAccessDenied();}}const walk=(dir:string,depth:number)=>{validate();if(depth>MAX_DEPTH)throw new ChatAccessDenied();canonical(dir,root);const entries=[];const handle=opendirSync(dir);try{for(;;){validate();const item=handle.readSync();if(!item)break;if(++budget.entries>MAX_ENTRIES)throw new ChatAccessDenied();entries.push(item);}}finally{handle.closeSync();}for(const item of entries.sort((a,b)=>compare(a.name,b.name))){validate();const absolute=resolve(dir,item.name);if(item.isSymbolicLink())throw new ChatAccessDenied();if(item.isDirectory()){walk(absolute,depth+1);continue;}const candidate=item.isFile()&&(item.name==='SKILL.md'||depth===0&&item.name.endsWith('.md'));if(!candidate)continue;const value=read(absolute,root),meta=frontmatter(value.text,absolute,root);if(!meta)continue;if(++budget.skills>MAX_SKILLS)throw new ChatAccessDenied();output.push({...meta,provenance,source:relative(root,absolute).split(sep).join('/'),sha256:hash(value.bytes)});}};try{walk(root,0);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')throw new ChatAccessDenied();if(error instanceof ChatAccessDenied)throw error;throw new ChatAccessDenied();}return output;};

/** Fixed packaged-first inventory matching Pi's first-found collision behavior. */
export function readFamilySkillProvenance():FamilySkillProvenance[]{const mode=readAccessConfig().mode,workspace=getWorkspaceDir();let denied=false;const validate=()=>{try{if(denied||mode!=='family-shared'||readAccessConfig().mode!==mode||getWorkspaceDir()!==workspace)throw new ChatAccessDenied();}catch(error){denied=true;throw error;}};validate();const packaged=resolve(import.meta.dir,'../../skills'),shared=resolve(workspace,'.pi','skills'),budget:ScanBudget={entries:0,skills:0},rows=[...scan(packaged,'packaged',validate,budget),...scan(shared,'shared-workspace',validate,budget,true)],groups=new Map<string,typeof rows>();for(const row of rows){const group=groups.get(row.name)??[];group.push(row);groups.set(row.name,group);}const result:FamilySkillProvenance[]=[];for(const row of rows){const group=groups.get(row.name)!,winner=group[0]!;result.push({...row,selected:row===winner,collision_with:group.filter(v=>v!==row).map(v=>`${v.provenance}:${v.source}`)});}validate();return result;}
