import {afterEach,beforeEach,expect,test} from 'bun:test';import {linkSync,mkdirSync,symlinkSync,writeFileSync} from 'node:fs';import {join} from 'node:path';
import {createTempWorkspace,setEnv} from '../helpers.js';import {readFamilySkillProvenance} from '../../src/core/family-skill-provenance.js';import {ChatAccessDenied} from '../../src/db/session-ownership.js';
let ws:ReturnType<typeof createTempWorkspace>,restore:()=>void,config:string;const mode=(m:string)=>writeFileSync(config,m==='bad'?'{':JSON.stringify({domains:{access:{mode:m}}}));
function skill(dir:string,name:string,description:string){mkdirSync(dir,{recursive:true});writeFileSync(join(dir,'SKILL.md'),`---\nname: ${name}\ndescription: ${description}\n---\n\nPRIVATE BODY\n`);}
beforeEach(()=>{ws=createTempWorkspace('skill-provenance-');restore=setEnv({PICLAW_WORKSPACE:ws.workspace,PICLAW_STORE:ws.store,PICLAW_DATA:ws.data});mkdirSync(join(ws.workspace,'.piclaw'));config=join(ws.workspace,'.piclaw/config.json');mode('family-shared');});afterEach(()=>{restore();ws.cleanup();});
test('inventory separates packaged and shared provenance with packaged-first collision reporting and no bodies',()=>{skill(join(ws.workspace,'.pi/skills/schedule'),'schedule','Workspace collision');skill(join(ws.workspace,'.pi/skills/family-helper'),'family-helper','Shared helper');const rows=readFamilySkillProvenance(),schedule=rows.filter(v=>v.name==='schedule'),helper=rows.find(v=>v.name==='family-helper')!;expect(schedule.length).toBeGreaterThanOrEqual(2);expect(schedule[0]).toMatchObject({provenance:'packaged',selected:true});expect(schedule.find(v=>v.provenance==='shared-workspace')).toMatchObject({selected:false,source:'schedule/SKILL.md'});expect(helper).toMatchObject({provenance:'shared-workspace',selected:true,description:'Shared helper',source:'family-helper/SKILL.md'});const text=JSON.stringify(rows);expect(text).not.toContain('PRIVATE BODY');expect(text).not.toContain(ws.workspace);for(const row of rows)expect(row.sha256).toMatch(/^[a-f0-9]{64}$/);});
test('discovery matches Pi for root Markdown, rich frontmatter, fallback names and warning-only names',()=>{const root=join(ws.workspace,'.pi/skills');skill(join(root,'z-last'),'z-last','Z');skill(join(root,'a-first'),'a-first','A');skill(join(root,'invalid'),'Bad Name','Warning only');mkdirSync(root,{recursive:true});writeFileSync(join(root,'root.md'),'---\r\nname: root-skill\r\ndescription: root CRLF\r\n---\r\nbody');mkdirSync(join(root,'folded'),{recursive:true});writeFileSync(join(root,'folded/SKILL.md'),'\ufeff---\nname: folded\ndescription: >-\n  folded description\n---\nbody');mkdirSync(join(root,'fallback'),{recursive:true});writeFileSync(join(root,'fallback/SKILL.md'),'---\ndescription: fallback name\n---\nbody');mkdirSync(join(root,'ignored'),{recursive:true});writeFileSync(join(root,'ignored/nested.md'),'---\nname: nested\ndescription: ignored nested file\n---\nbody');const first=readFamilySkillProvenance(),second=readFamilySkillProvenance();expect(second).toEqual(first);const shared=first.filter(v=>v.provenance==='shared-workspace');expect(shared.map(v=>v.name)).toEqual(['a-first','fallback','folded','Bad Name','root-skill','z-last']);expect(shared.find(v=>v.name==='folded')?.description).toBe('folded description');expect(shared.some(v=>v.name==='nested')).toBe(false);});
test('symlinked workspace skill trees fail closed instead of enumerating outside content',()=>{mkdirSync(join(ws.workspace,'.pi/skills'),{recursive:true});symlinkSync('/tmp',join(ws.workspace,'.pi/skills/escape'));expect(()=>readFamilySkillProvenance()).toThrow(ChatAccessDenied);});
test('hard-linked skill files fail closed',()=>{const root=join(ws.workspace,'.pi/skills'),source=join(ws.workspace,'outside.md');mkdirSync(root,{recursive:true});writeFileSync(source,'---\nname: linked\ndescription: linked\n---\nbody');linkSync(source,join(root,'linked.md'));expect(()=>readFamilySkillProvenance()).toThrow(ChatAccessDenied);});
test('entry and valid-skill limits are global across packaged and shared roots',()=>{const root=join(ws.workspace,'.pi/skills');mkdirSync(root,{recursive:true});for(let i=0;i<2000;i++)writeFileSync(join(root,`entry-${String(i).padStart(4,'0')}`),'x');expect(()=>readFamilySkillProvenance()).toThrow(ChatAccessDenied);ws.cleanup();ws=createTempWorkspace('skill-provenance-bounds-');restore();restore=setEnv({PICLAW_WORKSPACE:ws.workspace,PICLAW_STORE:ws.store,PICLAW_DATA:ws.data});mkdirSync(join(ws.workspace,'.piclaw'),{recursive:true});config=join(ws.workspace,'.piclaw/config.json');mode('family-shared');for(let i=0;i<500;i++)skill(join(ws.workspace,'.pi/skills',`skill-${String(i).padStart(3,'0')}`),`skill-${String(i).padStart(3,'0')}`,'bounded');expect(()=>readFamilySkillProvenance()).toThrow(ChatAccessDenied);});
test('invalid, single-user and isolated modes deny inventory',()=>{for(const value of ['single-user','isolated-containers','bad']){mode(value);expect(()=>readFamilySkillProvenance()).toThrow();}});
test('directory ordering uses Unicode code points rather than UTF-16 code units',()=>{skill(join(ws.workspace,'.pi/skills/\ue000'),'same-skill','BMP path');skill(join(ws.workspace,'.pi/skills/😀'),'same-skill','Astral path');const rows=readFamilySkillProvenance().filter(v=>v.name==='same-skill');expect(rows.map(v=>v.source)).toEqual(['\ue000/SKILL.md','😀/SKILL.md']);expect(rows.map(v=>v.selected)).toEqual([true,false]);});
