import {afterEach,beforeEach,expect,test} from 'bun:test';
import {mkdirSync,writeFileSync} from 'node:fs';import {join} from 'node:path';
import {createTempWorkspace,setEnv} from '../../helpers.js';
import {closeDatabase,getDb,initDatabase} from '../../../src/db/connection.js';import {createWebSession} from '../../../src/db/web-sessions.js';import {getUser,updateUser} from '../../../src/db/users.js';
import {provisionFamilyAccount,updateManagedAccount} from '../../../src/db/account-administration.js';import {resolveRequestPrincipal} from '../../../src/channels/web/auth/principal.js';import type {AuthenticatedPrincipal} from '../../../src/core/access-types.js';
import {storeMessage} from '../../../src/db/messages.js';import {RequestRouterService} from '../../../src/channels/web/request-router-service.js';import {WebAuthGateway} from '../../../src/channels/web/auth/auth-gateway.js';import {WebauthnChallengeTracker} from '../../../src/channels/web/auth/webauthn-challenges.js';import {TotpFailureTracker} from '../../../src/channels/web/auth/totp-failure-tracker.js';
let ws:ReturnType<typeof createTempWorkspace>,restore:()=>void,alice:AuthenticatedPrincipal,bob:AuthenticatedPrincipal;
function actor(id:string){const login=createWebSession(`token-${id}`,id,3600,'passkey');return resolveRequestPrincipal(new Request('https://family.local',{headers:{cookie:'piclaw_session=fixture'}}),{mode:'family-shared',authEnabled:true},{getSession:()=>login,getUser:()=>getUser(getDb(),id),getLocalDisplayName:()=> 'unused'})!;}
function router(events:any[]=[],wakes:any[]=[]){const json=(body:unknown,status=200)=>Response.json(body,{status});const authGateway=new WebAuthGateway({accessMode:'family-shared',passkeyMode:'',totpSecret:'',internalSecret:'',sessionTtlSeconds:3600,hasTls:true},{json,challenges:new WebauthnChallengeTracker(),failureTracker:new TotpFailureTracker()});return new RequestRouterService({json,authGateway,broadcastEvent:(...args:any[])=>events.push(args),resumeChat:(...args:any[])=>wakes.push(args)} as any,'family-shared');}
function req(path:string,body:unknown,actor=alice){return new Request(`https://family.local${path}`,{method:path.includes('/annotations')?'PATCH':'POST',headers:{cookie:`piclaw_session=token-${actor.userId}`,origin:'https://family.local','x-piclaw-account-id':actor.userId,'x-piclaw-login-id':actor.authentication.sessionId!,'content-type':'application/json'},body:JSON.stringify(body)});}
function card(owner:AuthenticatedPrincipal,id:string){return storeMessage({id,chat_jid:owner.homeChatJid!,sender:'web-agent',sender_name:'PiClaw',content:'Choose',timestamp:new Date().toISOString(),is_bot_message:true,content_blocks:[{type:'adaptive_card',card_id:`card-${id}`,state:'active',payload:{type:'AdaptiveCard',version:'1.5',body:[],actions:[{type:'Action.Submit',title:'Choose'}]}}]});}
beforeEach(()=>{ws=createTempWorkspace('family-rich-actions-');restore=setEnv({PICLAW_WORKSPACE:ws.workspace,PICLAW_STORE:ws.store,PICLAW_DATA:ws.data});mkdirSync(join(ws.workspace,'.piclaw'));writeFileSync(join(ws.workspace,'.piclaw/config.json'),JSON.stringify({domains:{access:{mode:'family-shared'}}}));closeDatabase();initDatabase();const admin=actor('default');for(const name of ['alice','bob']){const u=provisionFamilyAccount(getDb(),admin,{username:name,displayName:name});getDb().query("INSERT INTO webauthn_credentials(user_id,rp_id,credential_id,public_key) VALUES (?,'family.local',?,'key')").run(u.id,name);updateManagedAccount(getDb(),admin,u.id,{enabled:true},{totp:false,passkey:true,rpId:'family.local'});if(name==='alice')alice=actor(u.id);else bob=actor(u.id);}});afterEach(()=>{closeDatabase();restore();ws.cleanup();});

test('owned annotation updates use exact message/chat and pinned live account',async()=>{const events:any[]=[],r=router(events),own=card(alice,'alice-card'),foreign=card(bob,'bob-card');const annotations=[{type:'highlight',text:'Choose',textOffset:0,color:'yellow'}];
  const ok=await r.handle(req(`/post/${own}/annotations?chat_jid=${encodeURIComponent(alice.homeChatJid!)}`,{annotations}));expect(ok.status).toBe(200);expect((await ok.json()).annotations).toEqual(annotations);expect(JSON.parse((getDb().query('SELECT annotations FROM messages WHERE rowid=?').get(own) as any).annotations)).toEqual(annotations);
  expect((await r.handle(req(`/post/${foreign}/annotations?chat_jid=${encodeURIComponent(bob.homeChatJid!)}`,{annotations}))).status).toBe(403);expect((await r.handle(req(`/post/${own}/annotations?chat_jid=${encodeURIComponent(alice.homeChatJid!)}`,{annotations,owner:'bob'}))).status).toBe(400);expect(events).toHaveLength(1);expect(events[0][0]).toBe('interaction_updated');expect(events[0][1]).toMatchObject({id:own,chat_jid:alice.homeChatJid,data:{content:'Choose',annotations}});
});

test('generic owned card submit atomically completes source and admits one idempotent turn',async()=>{const events:any[]=[],wakes:any[]=[],r=router(events,wakes),source=card(alice,'alice-card');const body={post_id:source,thread_id:source,chat_jid:alice.homeChatJid,card_id:'card-alice-card',request_id:'card-request',action:{type:'Action.Submit',title:'Choose',data:{choice:'A',__private:'drop'}}};
  const first=await r.handle(req('/agent/card-action',body));expect(first.status).toBe(201);const value=await first.json();expect(value.created).toBe(true);expect(value.user_message.data.content).toContain('choice: A');expect(value.user_message.data.content).not.toContain('__private');expect(value.user_message.data.content_blocks[0]).toMatchObject({type:'adaptive_card_submission',card_id:'card-alice-card',source_post_id:source,data:{choice:'A'}});
  const sourceBlocks=JSON.parse((getDb().query('SELECT content_blocks FROM messages WHERE rowid=?').get(source) as any).content_blocks);expect(sourceBlocks[0].state).toBe('completed');expect(events.map(event=>event[0])).toEqual(['interaction_updated','new_post']);expect(events[0][1]).toMatchObject({id:source,chat_jid:alice.homeChatJid});expect(events[1][1]).toMatchObject({id:value.user_message.id,chat_jid:alice.homeChatJid});expect(wakes).toEqual([[alice.homeChatJid,source]]);
  expect((await r.handle(req('/agent/card-action',body))).status).toBe(200);expect((getDb().query('SELECT count(*) n FROM message_execution_authorities').get() as any).n).toBe(1);expect(events).toHaveLength(2);expect(wakes).toHaveLength(1);
});

test('card submit denies foreign inactive changed and privileged intent targets without mutation',async()=>{const r=router(),own=card(alice,'alice-card'),foreign=card(bob,'bob-card');const input=(patch:any={})=>({post_id:own,thread_id:own,chat_jid:alice.homeChatJid,card_id:'card-alice-card',request_id:`request-${crypto.randomUUID()}`,action:{type:'Action.Submit',title:'Choose',data:{choice:'A'}},...patch});
  expect((await r.handle(req('/agent/card-action',input({post_id:foreign,chat_jid:bob.homeChatJid,card_id:'card-bob-card'})))).status).toBe(403);expect((await r.handle(req('/agent/card-action',input({card_id:'missing'})))).status).toBe(403);expect((await r.handle(req('/agent/card-action',input({action:{type:'Action.Submit',title:'Choose',data:{intent:'login-step1'}}})))).status).toBe(403);
  updateUser(getDb(),alice.userId,{enabled:false});expect((await r.handle(req('/agent/card-action',input()))).status).toBe(401);expect((getDb().query('SELECT count(*) n FROM message_execution_authorities').get() as any).n).toBe(0);
});
